// Mapping FIS alpha-3 vers ISO alpha-2
const alpha3ToAlpha2Map: Record<string, string> = {
  FRA: "FR",
  ITA: "IT",
  SUI: "CH",
  GER: "DE",
  AUT: "AT",
  ESP: "ES",
  AND: "AD",
  USA: "US",
  CAN: "CA",
  NOR: "NO",
  SWE: "SE",
  FIN: "FI",
  GBR: "GB",
  SVK: "SK",
  SLO: "SI",
  CZE: "CZ",
  POL: "PL",
  CRO: "HR",
  BEL: "BE",
  NED: "NL",
  LIE: "LI",
  AUS: "AU",
  NZL: "NZ",
  RUS: "RU",
  JPN: "JP",
  CHN: "CN",
  KOR: "KR",
  ARG: "AR",
  BRA: "BR",
  BUL: "BG",
  HUN: "HU",
  LAT: "LV",
  EST: "EE",
  LTU: "LT",
  UKR: "UA",
  KAZ: "KZ",
  POR: "PT",
  ROM: "RO",
  SRB: "RS",
  TUR: "TR",
  MEX: "MX",
  GRE: "GR",
  DEN: "DK",
  LUX: "LU",
  MON: "MC",
  ISR: "IL",
  GEO: "GE",
  BIH: "BA",
  MKD: "MK",
  CYP: "CY",
  ARM: "AM",
  MDA: "MD",
  TPE: "TW",
  HKG: "HK",
  MAR: "MA",
  ALG: "DZ",
  RSA: "ZA",
  LBN: "LB",
  TUN: "TN",
  QAT: "QA",
  UAE: "AE",
  IND: "IN",
  PAK: "PK",
  THA: "TH",
  SIN: "SG",
  INA: "ID",
  MGL: "MN",
  KGZ: "KG",
  UZB: "UZ",
  MNE: "ME",
  PUR: "PR",
  ISL: "IS",
  IRL: "IE",
  BLR: "BY",
  // Ajoute d'autres si besoin
};

export const alpha3ToAlpha2 = (alpha3: string): string | undefined => {
  if (!alpha3) return undefined;
  return alpha3ToAlpha2Map[alpha3] || undefined;
};
export default alpha3ToAlpha2;
