-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TABLE `A_biogs` (
	`Recid` int AUTO_INCREMENT NOT NULL,
	`Competitorid` int NOT NULL DEFAULT 0,
	`Birthnation` varchar(5),
	`Birthplace` varchar(45),
	`Nickname` varchar(45),
	`Children` tinyint,
	`Residence` varchar(80),
	`Residencenation` varchar(5),
	`Education` varchar(100),
	`Occupation` varchar(100),
	`Languages` varchar(100),
	`Hobbies` varchar(100),
	`Websiteurl` varchar(100),
	`Height` decimal(5,2),
	`Weight` decimal(5,2),
	`Webcomments` varchar(200),
	`Comments` varchar(100),
	`Webdisplay` tinyint DEFAULT 1,
	`Clubnation` varchar(5),
	`Nationalcoach` varchar(50),
	`Nationalcoachnation` varchar(5),
	`Personalcoach` varchar(50),
	`Personalcoachnation` varchar(5),
	`Debut` int,
	`Nationaldebut` int,
	`Debutwcpoints` varchar(50),
	`Debutwc` varchar(50),
	`Debutwcpodium` varchar(50),
	`Othersports` varchar(150),
	`Majorinjuries` varchar(150),
	`Maritalstatus` varchar(30),
	`Skis` varchar(30),
	`Skis2` varchar(30),
	`Bindings` varchar(30),
	`Bindings2` varchar(30),
	`Boots` varchar(30),
	`Boots2` varchar(30),
	`Helmet` varchar(30),
	`Suit` varchar(30),
	`Gloves` varchar(30),
	`Glasses` varchar(30),
	`Poles` varchar(30),
	`Stance` varchar(1),
	`Photo` tinyint DEFAULT 0,
	`Marital` varchar(30),
	`Picture` blob,
	`Picturedate` datetime,
	`Lastupdate` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `A_biogs_Recid` PRIMARY KEY(`Recid`),
	CONSTRAINT `Compet` UNIQUE(`Competitorid`)
);
--> statement-breakpoint
CREATE TABLE `A_competitor` (
	`Competitorid` int AUTO_INCREMENT NOT NULL,
	`Personid` int,
	`Ipcid` int,
	`Type` varchar(100) DEFAULT 'athlete',
	`Sectorcode` char(3) NOT NULL DEFAULT '',
	`Fiscode` int,
	`Lastname` varchar(50),
	`Firstname` varchar(50),
	`Gender` char(1),
	`Birthdate` date,
	`Nationcode` varchar(5),
	`Nationalcode` varchar(15),
	`Skiclub` varchar(100),
	`Association` varchar(5),
	`Status` char(1),
	`Status_old` char(1),
	`Status_by` int,
	`Status_date` timestamp,
	`Statusnextlist` char(1),
	`Alternatenamecheck` varchar(50),
	`Fee` decimal(10,2),
	`Dateofcreation` date,
	`Createdby` int,
	`Injury` tinyint DEFAULT 0,
	`Version` int,
	`Compidmssql` int,
	`Carving` tinyint(4) unsigned zerofill DEFAULT 0,
	`Photo` tinyint NOT NULL DEFAULT 0,
	`Notallowed` tinyint DEFAULT 0,
	`Natteam` varchar(30),
	`Tragroup` varchar(30),
	`Published` int NOT NULL DEFAULT 1,
	`Doped` tinyint(1) DEFAULT 0,
	`Team` tinyint NOT NULL DEFAULT 0,
	`Photo_big` tinyint unsigned NOT NULL DEFAULT 0,
	`Data` json,
	`Lastupdateby` int,
	`Disciplines` json,
	`Deletedat` timestamp,
	`Lastupdate` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `A_competitor_Competitorid` PRIMARY KEY(`Competitorid`),
	CONSTRAINT `CompetitoridSector` UNIQUE(`Competitorid`,`Sectorcode`)
);
--> statement-breakpoint
CREATE TABLE `A_cup` (
	`Recid` int AUTO_INCREMENT NOT NULL,
	`Sectorcode` char(3) NOT NULL DEFAULT '',
	`Cupcode` varchar(10) NOT NULL,
	`Description` varchar(40) NOT NULL DEFAULT '',
	`Displayorder` smallint NOT NULL DEFAULT 0,
	`Inuse` char(1) NOT NULL DEFAULT '',
	`Published` tinyint,
	`Decimalprecision` tinyint unsigned,
	`CalculatedByCupsprocessor` tinyint unsigned NOT NULL DEFAULT 0,
	`Lastupdate` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `A_cup_Recid` PRIMARY KEY(`Recid`)
);
--> statement-breakpoint
CREATE TABLE `A_cupresult` (
	`Recid` int AUTO_INCREMENT NOT NULL,
	`Sectorcode` char(3) NOT NULL DEFAULT '',
	`Seasoncode` int NOT NULL DEFAULT 0,
	`Cupid` varchar(10) NOT NULL,
	`Disciplinecode` varchar(5) NOT NULL DEFAULT '',
	`Afterxrace` tinyint NOT NULL DEFAULT 0,
	`Competitorid` int NOT NULL DEFAULT 0,
	`Lastname` varchar(50),
	`Firstname` varchar(50),
	`Nationcode` varchar(5),
	`Gender` char(1) NOT NULL DEFAULT '',
	`Rank` int NOT NULL DEFAULT 0,
	`Points` decimal(10,2) DEFAULT '0.00',
	`Exaequo` char(200) DEFAULT '00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
	`Lastupdate` timestamp DEFAULT (CURRENT_TIMESTAMP),
	CONSTRAINT `A_cupresult_Recid` PRIMARY KEY(`Recid`)
);
--> statement-breakpoint
CREATE TABLE `A_discipline` (
	`Recid` int AUTO_INCREMENT NOT NULL,
	`Sectorcode` char(3) NOT NULL,
	`Disciplinecode` char(8) NOT NULL,
	`Description` varchar(50) NOT NULL,
	`Displayorder` smallint NOT NULL DEFAULT 0,
	`Disciplineid` smallint NOT NULL DEFAULT 0,
	`Inuse` char(1) NOT NULL,
	`Fispoints` tinyint NOT NULL DEFAULT 0,
	`Published` tinyint NOT NULL DEFAULT 0,
	`Disciplineforlist` char(8) NOT NULL DEFAULT '0',
	`Validforraces` tinyint NOT NULL DEFAULT 0,
	`Shortreport` tinyint NOT NULL DEFAULT 0,
	`ValidforOWG` tinyint NOT NULL DEFAULT 1,
	`ValidforWSC` tinyint NOT NULL DEFAULT 1,
	`Timeprecision` int DEFAULT 100,
	`Disciplineforcup` varchar(20),
	`Disciplinegroupid` int,
	`Lastupdate` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `A_discipline_Recid` PRIMARY KEY(`Recid`)
);
--> statement-breakpoint
CREATE TABLE `A_event` (
	`Eventid` int AUTO_INCREMENT NOT NULL,
	`Seasoncode` int NOT NULL DEFAULT 0,
	`Sectorcode` char(3) NOT NULL DEFAULT '',
	`Eventname` varchar(100),
	`Startdate` date,
	`Enddate` date,
	`Nationcodeplace` char(3) NOT NULL DEFAULT '',
	`Orgnationcode` char(3) NOT NULL DEFAULT '',
	`Place` varchar(40) NOT NULL DEFAULT '',
	`Published` tinyint NOT NULL DEFAULT 0,
	`OrgaddressL1` varchar(70),
	`OrgaddressL2` varchar(70),
	`OrgaddressL3` varchar(70),
	`OrgaddressL4` varchar(70),
	`Orgtel` varchar(50),
	`Orgmobile` varchar(50),
	`Orgfax` varchar(50),
	`OrgEmail` varchar(100),
	`Orgemailentries` varchar(100),
	`Orgemailaccomodation` varchar(100),
	`Orgemailtransportation` varchar(100),
	`OrgWebsite` varchar(200),
	`Socialmedia` varchar(250),
	`Eventnotes` varchar(100),
	`Languageused` char(1),
	`Td1id` int,
	`Td1name` varchar(30),
	`Td1nation` varchar(5),
	`Td2id` int,
	`Td2name` varchar(30),
	`Td2nation` varchar(5),
	`Orgfee` decimal(8,2),
	`Bill` tinyint,
	`Billdate` date,
	`Selcat` varchar(50),
	`Seldis` varchar(50),
	`Seldisl` varchar(50),
	`Seldism` varchar(50),
	`Dispdate` varchar(20),
	`Discomment` varchar(40),
	`Version` int,
	`Nationeventid` int,
	`Proveventid` int,
	`Mssql7id` int,
	`Results` tinyint DEFAULT 0,
	`Pdf` tinyint DEFAULT 0,
	`Topbanner` int,
	`Bottombanner` int,
	`Toplogo` int,
	`Bottomlogo` int,
	`Gallery` int,
	`Nextracedate` date,
	`Lastracedate` date,
	`TDletter` int DEFAULT 0,
	`Orgaddressid` int,
	`Tournament` tinyint DEFAULT 0,
	`Parenteventid` int,
	`Placeid` int,
	`Timezone` varchar(50),
	`Lastupdate` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `A_event_Eventid` PRIMARY KEY(`Eventid`)
);
--> statement-breakpoint
CREATE TABLE `A_listcategoryal` (
	`Recid` int AUTO_INCREMENT NOT NULL,
	`Listid` int NOT NULL DEFAULT 0,
	`Seasoncode` int NOT NULL DEFAULT 0,
	`Catcode` char(8),
	`Gender` char(1),
	`Minfispoints` decimal(8,2),
	`Maxfispoints` decimal(8,2),
	`Adder` decimal(8,2),
	`Version` int,
	`Lastupdate` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `A_listcategoryal_Recid` PRIMARY KEY(`Recid`)
);
--> statement-breakpoint
CREATE TABLE `A_listcategorycc` (
	`Recid` int AUTO_INCREMENT NOT NULL,
	`Listid` int NOT NULL DEFAULT 0,
	`Seasoncode` int NOT NULL DEFAULT 0,
	`Catcode` char(8),
	`Gender` char(1),
	`Minfispoints` decimal(8,2),
	`Maxfispoints` decimal(8,2),
	`Adder` decimal(8,2),
	`Version` int,
	`Lastupdate` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `A_listcategorycc_Recid` PRIMARY KEY(`Recid`)
);
--> statement-breakpoint
CREATE TABLE `A_listcategoryfs` (
	`Recid` int AUTO_INCREMENT NOT NULL,
	`Listid` int NOT NULL DEFAULT 0,
	`Seasoncode` int NOT NULL DEFAULT 0,
	`Catcode` char(8),
	`Gender` char(1),
	`Minfispoints` decimal(8,2),
	`Maxfispoints` decimal(8,2),
	`Adder` decimal(8,2),
	`Version` int,
	`Lastupdate` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `A_listcategoryfs_Recid` PRIMARY KEY(`Recid`)
);
--> statement-breakpoint
CREATE TABLE `A_listcategorygs` (
	`Recid` int AUTO_INCREMENT NOT NULL,
	`Listid` int NOT NULL DEFAULT 0,
	`Seasoncode` int NOT NULL DEFAULT 0,
	`Catcode` char(8),
	`Gender` char(1),
	`Minfispoints` decimal(8,2),
	`Maxfispoints` decimal(8,2),
	`Adder` decimal(8,2),
	`Version` int,
	`Lastupdate` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `A_listcategorygs_Recid` PRIMARY KEY(`Recid`)
);
--> statement-breakpoint
CREATE TABLE `A_listcategoryma` (
	`Recid` int AUTO_INCREMENT NOT NULL,
	`Listid` int NOT NULL DEFAULT 0,
	`Seasoncode` int NOT NULL DEFAULT 0,
	`Catcode` char(8),
	`Gender` char(1),
	`Minfispoints` decimal(8,2),
	`Maxfispoints` decimal(8,2),
	`Adder` decimal(8,2),
	`Version` int,
	`Lastupdate` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `A_listcategoryma_Recid` PRIMARY KEY(`Recid`)
);
--> statement-breakpoint
CREATE TABLE `A_listcategorysb` (
	`Recid` int AUTO_INCREMENT NOT NULL,
	`Listid` int NOT NULL DEFAULT 0,
	`Seasoncode` int NOT NULL DEFAULT 0,
	`Catcode` char(8),
	`Gender` char(1),
	`Minfispoints` decimal(8,2),
	`Maxfispoints` decimal(8,2),
	`Adder` decimal(8,2),
	`Version` int,
	`Lastupdate` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `A_listcategorysb_Recid` PRIMARY KEY(`Recid`)
);
--> statement-breakpoint
CREATE TABLE `A_listcategoryss` (
	`Recid` int AUTO_INCREMENT NOT NULL,
	`Listid` int NOT NULL DEFAULT 0,
	`Seasoncode` int NOT NULL DEFAULT 0,
	`Catcode` char(8),
	`Gender` char(1),
	`Minfispoints` decimal(8,2),
	`Maxfispoints` decimal(8,2),
	`Adder` decimal(8,2),
	`Version` int,
	`Lastupdate` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `A_listcategoryss_Recid` PRIMARY KEY(`Recid`)
);
--> statement-breakpoint
CREATE TABLE `A_listcategorytm` (
	`Recid` int AUTO_INCREMENT NOT NULL,
	`Listid` int NOT NULL DEFAULT 0,
	`Seasoncode` int NOT NULL DEFAULT 0,
	`Catcode` char(8),
	`Gender` char(1),
	`Minfispoints` decimal(8,2),
	`Maxfispoints` decimal(8,2),
	`Adder` decimal(8,2),
	`Version` int,
	`Lastupdate` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `A_listcategorytm_Recid` PRIMARY KEY(`Recid`)
);
--> statement-breakpoint
CREATE TABLE `A_listdefal` (
	`Listalid` int NOT NULL DEFAULT 0,
	`Listid` int AUTO_INCREMENT NOT NULL,
	`Seasoncode` int NOT NULL DEFAULT 0,
	`Listnumber` int NOT NULL DEFAULT 0,
	`Listname` varchar(50),
	`Speciallist` tinyint,
	`Printdeadline` date,
	`Calculationdate` date,
	`Startracedate` date,
	`Endracedate` date,
	`Validfrom` date,
	`Validto` date,
	`Published` tinyint,
	`Version` int,
	`Tocalculateat` datetime,
	`Lastupdate` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `A_listdefal_Listid` PRIMARY KEY(`Listid`)
);
--> statement-breakpoint
CREATE TABLE `A_listdefcc` (
	`Listalid` int NOT NULL DEFAULT 0,
	`Listid` int AUTO_INCREMENT NOT NULL,
	`Seasoncode` int NOT NULL DEFAULT 0,
	`Listnumber` int NOT NULL DEFAULT 0,
	`Listname` varchar(50),
	`Speciallist` tinyint,
	`Printdeadline` date,
	`Calculationdate` date,
	`Startracedate` date,
	`Endracedate` date,
	`Validfrom` date,
	`Validto` date,
	`Published` tinyint,
	`Version` int,
	`Tocalculateat` datetime,
	`Lastupdate` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `A_listdefcc_Listid` PRIMARY KEY(`Listid`)
);
--> statement-breakpoint
CREATE TABLE `A_listdeffs` (
	`Listalid` int NOT NULL DEFAULT 0,
	`Listid` int AUTO_INCREMENT NOT NULL,
	`Seasoncode` int NOT NULL DEFAULT 0,
	`Listnumber` int NOT NULL DEFAULT 0,
	`Listname` varchar(50),
	`Speciallist` tinyint,
	`Printdeadline` date,
	`Calculationdate` date,
	`Startracedate` date,
	`Endracedate` date,
	`Validfrom` date,
	`Validto` date,
	`Published` tinyint,
	`Version` int,
	`Tocalculateat` datetime,
	`Lastupdate` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `A_listdeffs_Listid` PRIMARY KEY(`Listid`)
);
--> statement-breakpoint
CREATE TABLE `A_listdefgs` (
	`Recid` int NOT NULL,
	`Listid` int AUTO_INCREMENT NOT NULL,
	`Seasoncode` int NOT NULL DEFAULT 0,
	`Listnumber` int NOT NULL DEFAULT 0,
	`Listname` varchar(50),
	`Speciallist` tinyint,
	`Printdeadline` date,
	`Calculationdate` date,
	`Startracedate` date,
	`Endracedate` date,
	`Validfrom` date,
	`Validto` date,
	`Published` tinyint,
	`Version` int,
	`Tocalculateat` datetime,
	`Lastupdate` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `A_listdefgs_Listid` PRIMARY KEY(`Listid`)
);
--> statement-breakpoint
CREATE TABLE `A_listdefma` (
	`Listalid` int NOT NULL DEFAULT 0,
	`Listid` int AUTO_INCREMENT NOT NULL,
	`Seasoncode` int NOT NULL DEFAULT 0,
	`Listnumber` int NOT NULL DEFAULT 0,
	`Listname` varchar(50),
	`Speciallist` tinyint,
	`Printdeadline` date,
	`Calculationdate` date,
	`Startracedate` date,
	`Endracedate` date,
	`Validfrom` date,
	`Validto` date,
	`Published` tinyint,
	`Version` int,
	`Tocalculateat` datetime,
	`Lastupdate` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `A_listdefma_Listid` PRIMARY KEY(`Listid`)
);
--> statement-breakpoint
CREATE TABLE `A_listdefsb` (
	`Listalid` int NOT NULL DEFAULT 0,
	`Listid` int AUTO_INCREMENT NOT NULL,
	`Seasoncode` int NOT NULL DEFAULT 0,
	`Listnumber` int NOT NULL DEFAULT 0,
	`Listname` varchar(50),
	`Speciallist` tinyint,
	`Printdeadline` date,
	`Calculationdate` date,
	`Startracedate` date,
	`Endracedate` date,
	`Validfrom` date,
	`Validto` date,
	`Published` tinyint,
	`Version` int,
	`Tocalculateat` datetime,
	`Lastupdate` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `A_listdefsb_Listid` PRIMARY KEY(`Listid`)
);
--> statement-breakpoint
CREATE TABLE `A_listdefss` (
	`Recid` int NOT NULL,
	`Listid` int AUTO_INCREMENT NOT NULL,
	`Seasoncode` int NOT NULL DEFAULT 0,
	`Listnumber` int NOT NULL DEFAULT 0,
	`Listname` varchar(50),
	`Speciallist` tinyint,
	`Printdeadline` date,
	`Calculationdate` date,
	`Startracedate` date,
	`Endracedate` date,
	`Validfrom` date,
	`Validto` date,
	`Published` tinyint,
	`Version` int,
	`Tocalculateat` datetime,
	`Lastupdate` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `A_listdefss_Listid` PRIMARY KEY(`Listid`)
);
--> statement-breakpoint
CREATE TABLE `A_listdeftm` (
	`Recid` int NOT NULL,
	`Listid` int AUTO_INCREMENT NOT NULL,
	`Seasoncode` int NOT NULL DEFAULT 0,
	`Listnumber` int NOT NULL DEFAULT 0,
	`Listname` varchar(50),
	`Speciallist` tinyint,
	`Printdeadline` date,
	`Calculationdate` date,
	`Startracedate` date,
	`Endracedate` date,
	`Validfrom` date,
	`Validto` date,
	`Published` tinyint,
	`Version` int,
	`Tocalculateat` datetime,
	`Lastupdate` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `A_listdeftm_Listid` PRIMARY KEY(`Listid`)
);
--> statement-breakpoint
CREATE TABLE `A_listdisciplineal` (
	`Recid` int AUTO_INCREMENT NOT NULL,
	`Listid` int NOT NULL DEFAULT 0,
	`Seasoncode` int NOT NULL DEFAULT 0,
	`Disciplinecode` char(5),
	`Gender` char(1),
	`Xvalue` decimal(8,2),
	`Yvalue` decimal(8,2),
	`Zvalue` decimal(8,2) NOT NULL DEFAULT '0.00',
	`Minpenalty` decimal(8,2),
	`Maxpenalty` decimal(8,2),
	`Fvalue` decimal(8,2),
	`Maxpoints` decimal(8,2),
	`Injuryminpen` decimal(8,2),
	`Injurymaxpen` decimal(8,2),
	`Injurypercentage` decimal(8,2),
	`Version` int,
	`Adder0` int DEFAULT 0,
	`Adder1` int DEFAULT 0,
	`Adder2` int DEFAULT 0,
	`Adder3` int DEFAULT 0,
	`Adder4` int DEFAULT 0,
	`Adder5` int DEFAULT 0,
	`Adder6` int DEFAULT 0,
	`Lastupdate` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `A_listdisciplineal_Recid` PRIMARY KEY(`Recid`)
);
--> statement-breakpoint
CREATE TABLE `A_listdisciplinetm` (
	`Recid` int AUTO_INCREMENT NOT NULL,
	`Listid` int NOT NULL DEFAULT 0,
	`Seasoncode` int NOT NULL DEFAULT 0,
	`Disciplinecode` char(5),
	`Gender` char(1),
	`Xvalue` decimal(8,2),
	`Yvalue` decimal(8,2),
	`Zvalue` decimal(8,2) NOT NULL DEFAULT '0.00',
	`Minpenalty` decimal(8,2),
	`Maxpenalty` decimal(8,2),
	`Fvalue` decimal(8,2),
	`Maxpoints` decimal(8,2),
	`Injuryminpen` decimal(8,2),
	`Injurymaxpen` decimal(8,2),
	`Injurypercentage` decimal(8,2),
	`Version` int,
	`Adder0` int DEFAULT 0,
	`Adder1` int DEFAULT 0,
	`Adder2` int DEFAULT 0,
	`Adder3` int DEFAULT 0,
	`Adder4` int DEFAULT 0,
	`Adder5` int DEFAULT 0,
	`Adder6` int DEFAULT 0,
	`Lastupdate` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `A_listdisciplinetm_Recid` PRIMARY KEY(`Recid`)
);
--> statement-breakpoint
CREATE TABLE `A_listresultal` (
	`Recid` int AUTO_INCREMENT NOT NULL,
	`Listid` int NOT NULL DEFAULT 0,
	`Competitorid` int NOT NULL DEFAULT 0,
	`Disciplinecode` char(3),
	`Fispoints` decimal(8,2),
	`Position` int,
	`Penalty` char(1),
	`Active` char(1),
	`Avenumresults` int,
	`Fixedbyfis` tinyint,
	`Raceid1` int,
	`Raceid2` int,
	`Raceid3` int,
	`Version` int,
	`Pointspreviouslist` decimal(8,2),
	`pourcentpreviouslist` decimal(8,2) DEFAULT '0.00',
	`Countlistsamestatus` int DEFAULT 0,
	`pourcent` decimal(8,2) DEFAULT '0.00',
	`Realpoints` decimal(8,2),
	`blessevalide` int DEFAULT 1,
	`Youthpoints` decimal(11,2),
	`Lastupdate` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `A_listresultal_Recid` PRIMARY KEY(`Recid`)
);
--> statement-breakpoint
CREATE TABLE `A_listresultcc` (
	`Recid` int AUTO_INCREMENT NOT NULL,
	`Listid` int NOT NULL DEFAULT 0,
	`Competitorid` int NOT NULL DEFAULT 0,
	`Disciplinecode` char(3),
	`Fispoints` decimal(8,2),
	`Position` int,
	`Penalty` char(1),
	`Active` char(1),
	`Avenumresults` int,
	`Fixedbyfis` tinyint,
	`Raceid1` int,
	`Raceid2` int,
	`Raceid3` int,
	`Raceid4` int,
	`Raceid5` int,
	`Raceid6` int,
	`Version` int,
	`Youthpoints` decimal(11,2),
	`Lastupdate` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `A_listresultcc_Recid` PRIMARY KEY(`Recid`)
);
--> statement-breakpoint
CREATE TABLE `A_listresultfs` (
	`Recid` int AUTO_INCREMENT NOT NULL,
	`Listid` int NOT NULL DEFAULT 0,
	`Competitorid` int NOT NULL DEFAULT 0,
	`Disciplinecode` char(3),
	`Fispoints` decimal(8,2),
	`Position` int,
	`Penalty` char(1),
	`Active` char(1),
	`Avenumresults` int,
	`Fixedbyfis` tinyint,
	`Raceid1` int,
	`Raceid2` int,
	`Raceid3` int,
	`Raceid4` int,
	`Raceid5` int,
	`Raceid6` int,
	`Realpoints` decimal(8,2),
	`Version` int,
	`Lastupdate` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `A_listresultfs_Recid` PRIMARY KEY(`Recid`)
);
--> statement-breakpoint
CREATE TABLE `A_listresultgs` (
	`Recid` int AUTO_INCREMENT NOT NULL,
	`Listid` int NOT NULL DEFAULT 0,
	`Competitorid` int NOT NULL DEFAULT 0,
	`Disciplinecode` char(3),
	`Fispoints` decimal(8,2),
	`Position` int,
	`Penalty` char(1),
	`Active` char(1),
	`Avenumresults` int,
	`Fixedbyfis` tinyint,
	`Raceid1` int,
	`Raceid2` int,
	`Raceid3` int,
	`Version` int,
	`Pointsdebseason` decimal(8,2),
	`Realpoints` decimal(8,2),
	`Lastupdate` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `A_listresultgs_Recid` PRIMARY KEY(`Recid`)
);
--> statement-breakpoint
CREATE TABLE `A_listresultma` (
	`Recid` int AUTO_INCREMENT NOT NULL,
	`Listid` int NOT NULL DEFAULT 0,
	`Competitorid` int NOT NULL DEFAULT 0,
	`Disciplinecode` char(3),
	`Fispoints` decimal(8,2),
	`Position` int,
	`Penalty` char(1),
	`Active` char(1),
	`Avenumresults` int,
	`Fixedbyfis` tinyint,
	`Raceid1` int,
	`Raceid2` int,
	`Raceid3` int,
	`Version` int,
	`Pointspreviouslist` decimal(8,2),
	`pourcentpreviouslist` decimal(8,2),
	`Countlistsamestatus` int DEFAULT 0,
	`pourcent` decimal(8,2) DEFAULT '0.00',
	`Realpoints` decimal(8,2),
	`Lastupdate` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `A_listresultma_Recid` PRIMARY KEY(`Recid`)
);
--> statement-breakpoint
CREATE TABLE `A_listresultsb` (
	`Recid` int AUTO_INCREMENT NOT NULL,
	`Listid` int NOT NULL DEFAULT 0,
	`Competitorid` int NOT NULL DEFAULT 0,
	`Disciplinecode` char(3),
	`Fispoints` decimal(8,2),
	`Position` int,
	`Penalty` char(1),
	`Active` char(1),
	`Avenumresults` int,
	`Fixedbyfis` tinyint,
	`Raceid1` int,
	`Raceid2` int,
	`Raceid3` int,
	`Realpoints` decimal(8,2),
	`Version` int,
	`Ties` char(30),
	`Lastupdate` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `A_listresultsb_Recid` PRIMARY KEY(`Recid`)
);
--> statement-breakpoint
CREATE TABLE `A_listresultss` (
	`Recid` int AUTO_INCREMENT NOT NULL,
	`Listid` int NOT NULL DEFAULT 0,
	`Competitorid` int NOT NULL DEFAULT 0,
	`Disciplinecode` char(3),
	`Fispoints` decimal(8,2),
	`Position` int,
	`Penalty` char(1),
	`Active` char(1),
	`Avenumresults` int,
	`Fixedbyfis` tinyint,
	`Raceid1` int,
	`Raceid2` int,
	`Raceid3` int,
	`Version` int,
	`Pointspreviouslist` decimal(8,2),
	`pourcentpreviouslist` decimal(8,2) DEFAULT '0.00',
	`Countlistsamestatus` int DEFAULT 0,
	`pourcent` decimal(8,2) DEFAULT '0.00',
	`Realpoints` decimal(8,2),
	`blessevalide` int DEFAULT 1,
	`Lastupdate` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `A_listresultss_Recid` PRIMARY KEY(`Recid`)
);
--> statement-breakpoint
CREATE TABLE `A_listresulttm` (
	`Recid` int AUTO_INCREMENT NOT NULL,
	`Listid` int NOT NULL DEFAULT 0,
	`Competitorid` int NOT NULL DEFAULT 0,
	`Disciplinecode` char(3),
	`Fispoints` decimal(8,2),
	`Position` int,
	`Penalty` char(1),
	`Active` char(1),
	`Avenumresults` int,
	`Fixedbyfis` tinyint,
	`Raceid1` int,
	`Raceid2` int,
	`Raceid3` int,
	`Version` int,
	`Pointspreviouslist` decimal(8,2),
	`pourcentpreviouslist` decimal(8,2) DEFAULT '0.00',
	`Countlistsamestatus` int DEFAULT 0,
	`pourcent` decimal(8,2) DEFAULT '0.00',
	`Realpoints` decimal(8,2),
	`blessevalide` int DEFAULT 1,
	`Youthpoints` decimal(11,2),
	`Lastupdate` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `A_listresulttm_Recid` PRIMARY KEY(`Recid`)
);
--> statement-breakpoint
CREATE TABLE `A_raceal` (
	`Raceid` int AUTO_INCREMENT NOT NULL,
	`Eventid` int NOT NULL DEFAULT 0,
	`Seasoncode` int NOT NULL DEFAULT 0,
	`Racecodex` int unsigned,
	`Disciplineid` tinyint,
	`Disciplinecode` char(8),
	`Catcode` varchar(8),
	`Catcode2` varchar(5),
	`Catcode3` varchar(5),
	`Catcode4` varchar(5),
	`Gender` char(1),
	`Racedate` date,
	`Starteventdate` date,
	`Description` varchar(80),
	`Place` varchar(40),
	`Nationcode` varchar(5),
	`Td1id` int,
	`Td1name` varchar(80),
	`Td1nation` char(3),
	`Td1code` int,
	`Td2id` int,
	`Td2name` varchar(80),
	`Td2nation` char(3),
	`Td2code` int,
	`Calstatuscode` char(1),
	`Procstatuscode` char(1),
	`Receiveddate` date,
	`Pursuit` tinyint,
	`Masse` tinyint,
	`Relay` tinyint,
	`Distance` varchar(10),
	`Hill` varchar(10),
	`Style` char(1),
	`Qualif` tinyint,
	`Finale` tinyint,
	`Homol` varchar(20),
	`Webcomment` varchar(40),
	`Displaystatus` varchar(15),
	`Fisinterncomment` varchar(30),
	`Published` tinyint,
	`Validforfispoints` tinyint,
	`Usedfislist` int,
	`Tolist` int,
	`Discforlistcode` char(8),
	`Calculatedpenalty` decimal(10,2),
	`Appliedpenalty` decimal(10,2),
	`Appliedscala` int,
	`Penscafixed` tinyint,
	`Version` int,
	`Nationraceid` int,
	`Provraceid` int,
	`Msql7evid` int,
	`Mssql7id` int,
	`Results` tinyint DEFAULT 0,
	`Pdf` tinyint DEFAULT 0,
	`Topbanner` int,
	`Bottombanner` int,
	`Toplogo` int,
	`Bottomlogo` int,
	`Gallery` int,
	`Indi` tinyint DEFAULT 0,
	`Team` tinyint DEFAULT 0,
	`Tabcount` int unsigned DEFAULT 0,
	`Columncount` int unsigned DEFAULT 0,
	`Level` varchar(10) DEFAULT '',
	`Hloc1` varchar(10),
	`Hloc2` varchar(10),
	`Hloc3` varchar(10),
	`Hcet1` varchar(10),
	`Hcet2` varchar(10),
	`Hcet3` varchar(10),
	`Live` tinyint,
	`Livestatus1` varchar(30),
	`Livestatus2` varchar(30),
	`Livestatus3` varchar(30),
	`Liveinfo1` varchar(255),
	`Liveinfo2` varchar(255),
	`Liveinfo3` varchar(255),
	`Passwd` varchar(10),
	`Timinglogo` varchar(15),
	`Validdate` date,
	`Noepr` int NOT NULL DEFAULT 0,
	`TDdoc` int DEFAULT 0,
	`Timingreport` int DEFAULT 0,
	`Special_cup_points` int DEFAULT 0,
	`Skip_wcsl` int DEFAULT 0,
	`Validforowg` int unsigned NOT NULL DEFAULT 0,
	`Lastupdate` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `A_raceal_Raceid` PRIMARY KEY(`Raceid`)
);
--> statement-breakpoint
CREATE TABLE `A_racecc` (
	`Raceid` int AUTO_INCREMENT NOT NULL,
	`Eventid` int NOT NULL DEFAULT 0,
	`Seasoncode` int NOT NULL DEFAULT 0,
	`Racecodex` int unsigned,
	`Disciplineid` tinyint,
	`Disciplinecode` char(8),
	`Catcode` varchar(8),
	`Catcode2` varchar(5),
	`Catcode3` varchar(5),
	`Catcode4` varchar(5),
	`Gender` char(1),
	`Racedate` date,
	`Starteventdate` date,
	`Description` varchar(80),
	`Place` varchar(40),
	`Nationcode` varchar(5),
	`Td1id` int,
	`Td1name` varchar(80),
	`Td1nation` char(3),
	`Td1code` int,
	`Td2id` int,
	`Td2name` varchar(80),
	`Td2nation` char(3),
	`Td2code` int,
	`Calstatuscode` char(1),
	`Procstatuscode` char(1),
	`Receiveddate` date,
	`Pursuit` tinyint NOT NULL DEFAULT 0,
	`Masse` tinyint NOT NULL DEFAULT 0,
	`Relay` tinyint NOT NULL DEFAULT 0,
	`Distance` varchar(10),
	`Hill` varchar(10),
	`Style` char(1),
	`Qualif` tinyint,
	`Finale` tinyint,
	`Homol` varchar(20),
	`Webcomment` varchar(40),
	`Displaystatus` varchar(15),
	`Fisinterncomment` varchar(30),
	`Published` tinyint,
	`Validforfispoints` tinyint,
	`Usedfislist` int,
	`Tolist` int,
	`Discforlistcode` char(8),
	`Calculatedpenalty` decimal(10,2),
	`Appliedpenalty` decimal(10,2),
	`Appliedscala` int,
	`Penscafixed` tinyint,
	`Version` int,
	`Nationraceid` int,
	`Provraceid` int,
	`Msql7evid` int,
	`Mssql7id` int,
	`Results` tinyint DEFAULT 0,
	`Pdf` tinyint DEFAULT 0,
	`Topbanner` int,
	`Bottombanner` int,
	`Toplogo` int,
	`Bottomlogo` int,
	`Gallery` int,
	`Indi` tinyint DEFAULT 0,
	`Team` tinyint NOT NULL DEFAULT 0,
	`Tabcount` int unsigned DEFAULT 0,
	`Columncount` int unsigned DEFAULT 0,
	`Level` varchar(10) DEFAULT '',
	`Hloc1` varchar(10),
	`Hloc2` varchar(10),
	`Hloc3` varchar(10),
	`Hcet1` varchar(10),
	`Hcet2` varchar(10),
	`Hcet3` varchar(10),
	`Live` tinyint,
	`Livestatus1` varchar(30),
	`Livestatus2` varchar(30),
	`Livestatus3` varchar(30),
	`Liveinfo1` varchar(255),
	`Liveinfo2` varchar(255),
	`Liveinfo3` varchar(255),
	`Passwd` varchar(10),
	`Timinglogo` varchar(15),
	`Validdate` date,
	`Noepr` int NOT NULL DEFAULT 0,
	`TDdoc` int DEFAULT 0,
	`Timingreport` int DEFAULT 0,
	`Special_cup_points` int DEFAULT 0,
	`Skip_wcsl` int DEFAULT 0,
	`Validforowg` int unsigned NOT NULL DEFAULT 0,
	`Lastupdate` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `A_racecc_Raceid` PRIMARY KEY(`Raceid`)
);
--> statement-breakpoint
CREATE TABLE `A_racefs` (
	`Raceid` int AUTO_INCREMENT NOT NULL,
	`Eventid` int NOT NULL DEFAULT 0,
	`Seasoncode` int NOT NULL DEFAULT 0,
	`Racecodex` int unsigned,
	`Disciplineid` tinyint,
	`Disciplinecode` char(8),
	`Catcode` varchar(8),
	`Catcode2` varchar(5),
	`Catcode3` varchar(5),
	`Catcode4` varchar(5),
	`Gender` char(1),
	`Racedate` date,
	`Starteventdate` date,
	`Description` varchar(80),
	`Place` varchar(40),
	`Nationcode` varchar(5),
	`Td1id` int,
	`Td1name` varchar(80),
	`Td1nation` char(3),
	`Td1code` int,
	`Td2id` int,
	`Td2name` varchar(80),
	`Td2nation` char(3),
	`Td2code` int,
	`Calstatuscode` char(1),
	`Procstatuscode` char(1),
	`Receiveddate` date,
	`Pursuit` tinyint,
	`Masse` tinyint,
	`Relay` tinyint,
	`Distance` varchar(10),
	`Hill` varchar(10),
	`Style` char(1),
	`Qualif` tinyint,
	`Finale` tinyint,
	`Homol` varchar(20),
	`Webcomment` varchar(40),
	`Displaystatus` varchar(15),
	`Fisinterncomment` varchar(30),
	`Published` tinyint,
	`Validforfispoints` tinyint,
	`Usedfislist` int,
	`Tolist` int,
	`Discforlistcode` char(8),
	`Calculatedpenalty` decimal(10,2),
	`Appliedpenalty` decimal(10,2),
	`Appliedscala` int,
	`Penscafixed` tinyint,
	`Version` int,
	`Nationraceid` int,
	`Provraceid` int,
	`Msql7evid` int,
	`Mssql7id` int,
	`Results` tinyint DEFAULT 0,
	`Pdf` tinyint DEFAULT 0,
	`Topbanner` int,
	`Bottombanner` int,
	`Toplogo` int,
	`Bottomlogo` int,
	`Gallery` int,
	`Indi` tinyint DEFAULT 0,
	`Team` tinyint DEFAULT 0,
	`Tabcount` int unsigned DEFAULT 0,
	`Columncount` int unsigned DEFAULT 0,
	`Level` varchar(10) DEFAULT '',
	`Hloc1` varchar(10),
	`Hloc2` varchar(10),
	`Hloc3` varchar(10),
	`Hcet1` varchar(10),
	`Hcet2` varchar(10),
	`Hcet3` varchar(10),
	`Live` tinyint,
	`Livestatus1` varchar(30),
	`Livestatus2` varchar(30),
	`Livestatus3` varchar(30),
	`Liveinfo1` varchar(255),
	`Liveinfo2` varchar(255),
	`Liveinfo3` varchar(255),
	`Passwd` varchar(10),
	`Timinglogo` varchar(15),
	`Validdate` date,
	`Noepr` int NOT NULL DEFAULT 0,
	`TDdoc` int DEFAULT 0,
	`Timingreport` int DEFAULT 0,
	`Special_cup_points` int DEFAULT 0,
	`Skip_wcsl` int DEFAULT 0,
	`Validforowg` int unsigned NOT NULL DEFAULT 0,
	`Lastupdate` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `A_racefs_Raceid` PRIMARY KEY(`Raceid`)
);
--> statement-breakpoint
CREATE TABLE `A_racejp` (
	`Raceid` int AUTO_INCREMENT NOT NULL,
	`Eventid` int NOT NULL DEFAULT 0,
	`Seasoncode` int NOT NULL DEFAULT 0,
	`Racecodex` int unsigned,
	`Disciplineid` tinyint,
	`Disciplinecode` char(8),
	`Catcode` varchar(8),
	`Catcode2` varchar(5),
	`Catcode3` varchar(5),
	`Catcode4` varchar(5),
	`Gender` char(1),
	`Racedate` date,
	`Starteventdate` date,
	`Description` varchar(80),
	`Place` varchar(40),
	`Nationcode` varchar(5),
	`Td1id` int,
	`Td1name` varchar(80),
	`Td1nation` char(3),
	`Td1code` int,
	`Td2id` int,
	`Td2name` varchar(80),
	`Td2nation` char(3),
	`Td2code` int,
	`Calstatuscode` char(1),
	`Procstatuscode` char(1),
	`Receiveddate` date,
	`Pursuit` tinyint,
	`Masse` tinyint,
	`Relay` tinyint NOT NULL DEFAULT 0,
	`Distance` varchar(10),
	`Hill` varchar(10),
	`Style` char(1),
	`Qualif` tinyint,
	`Finale` tinyint,
	`Homol` varchar(20),
	`Webcomment` varchar(40),
	`Displaystatus` varchar(15),
	`Fisinterncomment` varchar(30),
	`Published` tinyint,
	`Validforfispoints` tinyint,
	`Usedfislist` int,
	`Tolist` int,
	`Discforlistcode` char(8),
	`Calculatedpenalty` decimal(10,2),
	`Appliedpenalty` decimal(10,2),
	`Appliedscala` int,
	`Penscafixed` tinyint,
	`Version` int,
	`Nationraceid` int,
	`Provraceid` int,
	`Msql7evid` int,
	`Mssql7id` int,
	`Results` tinyint DEFAULT 0,
	`Pdf` tinyint DEFAULT 0,
	`Topbanner` int,
	`Bottombanner` int,
	`Toplogo` int,
	`Bottomlogo` int,
	`Gallery` int,
	`Indi` tinyint DEFAULT 0,
	`Team` tinyint DEFAULT 0,
	`Tabcount` int unsigned DEFAULT 0,
	`Columncount` int unsigned DEFAULT 0,
	`Level` varchar(10) DEFAULT '',
	`Hloc1` varchar(10),
	`Hloc2` varchar(10),
	`Hloc3` varchar(10),
	`Hcet1` varchar(10),
	`Hcet2` varchar(10),
	`Hcet3` varchar(10),
	`Live` tinyint,
	`Livestatus1` varchar(35),
	`Livestatus2` varchar(35),
	`Livestatus3` varchar(35),
	`Liveinfo1` varchar(255),
	`Liveinfo2` varchar(255),
	`Liveinfo3` varchar(255),
	`Passwd` varchar(10),
	`Timinglogo` varchar(15),
	`Validdate` date,
	`Noepr` int NOT NULL DEFAULT 0,
	`TDdoc` int DEFAULT 0,
	`Timingreport` int DEFAULT 0,
	`Special_cup_points` int DEFAULT 0,
	`Skip_wcsl` int DEFAULT 0,
	`Validforowg` int unsigned NOT NULL DEFAULT 0,
	`Lastupdate` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `A_racejp_Raceid` PRIMARY KEY(`Raceid`)
);
--> statement-breakpoint
CREATE TABLE `A_racema` (
	`Raceid` int AUTO_INCREMENT NOT NULL,
	`Eventid` int NOT NULL DEFAULT 0,
	`Seasoncode` int NOT NULL DEFAULT 0,
	`Racecodex` int unsigned,
	`Disciplineid` tinyint,
	`Disciplinecode` char(8),
	`Catcode` varchar(8),
	`Catcode2` varchar(5),
	`Catcode3` varchar(5),
	`Catcode4` varchar(5),
	`Gender` char(1),
	`Racedate` date,
	`Starteventdate` date,
	`Description` varchar(80),
	`Place` varchar(40),
	`Nationcode` varchar(5),
	`Td1id` int,
	`Td1name` varchar(80),
	`Td1nation` char(3),
	`Td1code` int,
	`Td2id` int,
	`Td2name` varchar(80),
	`Td2nation` char(3),
	`Td2code` int,
	`Calstatuscode` char(1),
	`Procstatuscode` char(1),
	`Receiveddate` date,
	`Pursuit` tinyint,
	`Masse` tinyint,
	`Relay` tinyint,
	`Distance` varchar(10),
	`Hill` varchar(10),
	`Style` char(1),
	`Qualif` tinyint,
	`Finale` tinyint,
	`Homol` varchar(20),
	`Webcomment` varchar(40),
	`Displaystatus` varchar(15),
	`Fisinterncomment` varchar(30),
	`Published` tinyint,
	`Validforfispoints` tinyint,
	`Usedfislist` int,
	`Tolist` int,
	`Discforlistcode` char(8),
	`Calculatedpenalty` decimal(10,2),
	`Appliedpenalty` decimal(10,2),
	`Appliedscala` int,
	`Penscafixed` tinyint,
	`Version` int,
	`Nationraceid` int,
	`Provraceid` int,
	`Msql7evid` int,
	`Mssql7id` int,
	`Results` tinyint DEFAULT 0,
	`Pdf` tinyint DEFAULT 0,
	`Topbanner` int,
	`Bottombanner` int,
	`Toplogo` int,
	`Bottomlogo` int,
	`Gallery` int,
	`Indi` tinyint DEFAULT 0,
	`Team` tinyint DEFAULT 0,
	`Tabcount` int unsigned DEFAULT 0,
	`Columncount` int unsigned DEFAULT 0,
	`Level` varchar(10) DEFAULT '',
	`Hloc1` varchar(10),
	`Hloc2` varchar(10),
	`Hloc3` varchar(10),
	`Hcet1` varchar(10),
	`Hcet2` varchar(10),
	`Hcet3` varchar(10),
	`Live` tinyint,
	`Livestatus1` varchar(30),
	`Livestatus2` varchar(30),
	`Livestatus3` varchar(30),
	`Liveinfo1` varchar(255),
	`Liveinfo2` varchar(255),
	`Liveinfo3` varchar(255),
	`Passwd` varchar(10),
	`Timinglogo` varchar(15),
	`Validdate` date,
	`Noepr` int NOT NULL DEFAULT 0,
	`TDdoc` int DEFAULT 0,
	`Timingreport` int DEFAULT 0,
	`Special_cup_points` int DEFAULT 0,
	`Skip_wcsl` int DEFAULT 0,
	`Validforowg` int unsigned NOT NULL DEFAULT 0,
	`Lastupdate` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `A_racema_Raceid` PRIMARY KEY(`Raceid`)
);
--> statement-breakpoint
CREATE TABLE `A_racenk` (
	`Raceid` int AUTO_INCREMENT NOT NULL,
	`Eventid` int NOT NULL DEFAULT 0,
	`Seasoncode` int NOT NULL DEFAULT 0,
	`Racecodex` int unsigned,
	`Disciplineid` tinyint,
	`Disciplinecode` char(8),
	`Catcode` varchar(8),
	`Catcode2` varchar(5),
	`Catcode3` varchar(5),
	`Catcode4` varchar(5),
	`Gender` char(1),
	`Racedate` date,
	`Starteventdate` date,
	`Description` varchar(80),
	`Place` varchar(40),
	`Nationcode` varchar(5),
	`Td1id` int,
	`Td1name` varchar(80),
	`Td1nation` char(3),
	`Td1code` int,
	`Td2id` int,
	`Td2name` varchar(80),
	`Td2nation` char(3),
	`Td2code` int,
	`Calstatuscode` char(1),
	`Procstatuscode` char(1),
	`Receiveddate` date,
	`Pursuit` tinyint,
	`Masse` tinyint,
	`Relay` tinyint,
	`Distance` varchar(10),
	`Hill` varchar(10),
	`Style` char(1),
	`Qualif` tinyint,
	`Finale` tinyint,
	`Homol` varchar(20),
	`Webcomment` varchar(40),
	`Displaystatus` varchar(15),
	`Fisinterncomment` varchar(30),
	`Published` tinyint,
	`Validforfispoints` tinyint,
	`Usedfislist` int,
	`Tolist` int,
	`Discforlistcode` char(8),
	`Calculatedpenalty` decimal(10,2),
	`Appliedpenalty` decimal(10,2),
	`Appliedscala` int,
	`Penscafixed` tinyint,
	`Version` int,
	`Nationraceid` int,
	`Provraceid` int,
	`Msql7evid` int,
	`Mssql7id` int,
	`Results` tinyint DEFAULT 0,
	`Pdf` tinyint DEFAULT 0,
	`Topbanner` int,
	`Bottombanner` int,
	`Toplogo` int,
	`Bottomlogo` int,
	`Gallery` int,
	`Indi` tinyint DEFAULT 0,
	`Team` tinyint DEFAULT 0,
	`Tabcount` int unsigned DEFAULT 0,
	`Columncount` int unsigned DEFAULT 0,
	`Level` varchar(10) DEFAULT '',
	`Hloc1` varchar(10),
	`Hloc2` varchar(10),
	`Hloc3` varchar(10),
	`Hcet1` varchar(10),
	`Hcet2` varchar(10),
	`Hcet3` varchar(10),
	`Live` tinyint,
	`Livestatus1` varchar(30),
	`Livestatus2` varchar(30),
	`Livestatus3` varchar(30),
	`Liveinfo1` varchar(255),
	`Liveinfo2` varchar(255),
	`Liveinfo3` varchar(255),
	`Passwd` varchar(10),
	`Timinglogo` varchar(15),
	`Validdate` date,
	`Noepr` int NOT NULL DEFAULT 0,
	`TDdoc` int DEFAULT 0,
	`Timingreport` int DEFAULT 0,
	`Special_cup_points` int DEFAULT 0,
	`Skip_wcsl` int DEFAULT 0,
	`Validforowg` int unsigned NOT NULL DEFAULT 0,
	`Lastupdate` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `A_racenk_Raceid` PRIMARY KEY(`Raceid`)
);
--> statement-breakpoint
CREATE TABLE `A_racesb` (
	`Raceid` int AUTO_INCREMENT NOT NULL,
	`Eventid` int NOT NULL DEFAULT 0,
	`Seasoncode` int NOT NULL DEFAULT 0,
	`Racecodex` int unsigned,
	`Disciplineid` tinyint,
	`Disciplinecode` char(8),
	`Catcode` varchar(8),
	`Catcode2` varchar(5),
	`Catcode3` varchar(5),
	`Catcode4` varchar(5),
	`Gender` char(1),
	`Racedate` date,
	`Starteventdate` date,
	`Description` varchar(80),
	`Place` varchar(40),
	`Nationcode` varchar(5),
	`Td1id` int,
	`Td1name` varchar(80),
	`Td1nation` char(3),
	`Td1code` int,
	`Td2id` int,
	`Td2name` varchar(80),
	`Td2nation` char(3),
	`Td2code` int,
	`Calstatuscode` char(1),
	`Procstatuscode` char(1),
	`Receiveddate` date,
	`Pursuit` tinyint,
	`Masse` tinyint,
	`Relay` tinyint,
	`Distance` varchar(10),
	`Hill` varchar(10),
	`Style` char(1),
	`Qualif` tinyint,
	`Finale` tinyint,
	`Homol` varchar(20),
	`Webcomment` varchar(40),
	`Displaystatus` varchar(15),
	`Fisinterncomment` varchar(30),
	`Published` tinyint,
	`Validforfispoints` tinyint,
	`Usedfislist` int,
	`Tolist` int,
	`Discforlistcode` char(8),
	`Calculatedpenalty` decimal(10,2),
	`Appliedpenalty` decimal(10,2),
	`Appliedscala` int,
	`Penscafixed` tinyint,
	`Version` int,
	`Nationraceid` int,
	`Provraceid` int,
	`Msql7evid` int,
	`Mssql7id` int,
	`Results` tinyint DEFAULT 0,
	`Pdf` tinyint DEFAULT 0,
	`Topbanner` int,
	`Bottombanner` int,
	`Toplogo` int,
	`Bottomlogo` int,
	`Gallery` int,
	`Indi` tinyint DEFAULT 0,
	`Team` tinyint DEFAULT 0,
	`Tabcount` int unsigned DEFAULT 0,
	`Columncount` int unsigned DEFAULT 0,
	`Level` varchar(10) DEFAULT '',
	`Hloc1` varchar(10),
	`Hloc2` varchar(10),
	`Hloc3` varchar(10),
	`Hcet1` varchar(10),
	`Hcet2` varchar(10),
	`Hcet3` varchar(10),
	`Live` tinyint,
	`Livestatus1` varchar(30),
	`Livestatus2` varchar(30),
	`Livestatus3` varchar(30),
	`Liveinfo1` varchar(255),
	`Liveinfo2` varchar(255),
	`Liveinfo3` varchar(255),
	`Passwd` varchar(10),
	`Timinglogo` varchar(15),
	`Validdate` date,
	`Noepr` int NOT NULL DEFAULT 0,
	`TDdoc` int DEFAULT 0,
	`Timingreport` int DEFAULT 0,
	`Special_cup_points` int DEFAULT 0,
	`Skip_wcsl` int DEFAULT 0,
	`Validforowg` int unsigned NOT NULL DEFAULT 0,
	`Lastupdate` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `A_racesb_Raceid` PRIMARY KEY(`Raceid`)
);
--> statement-breakpoint
CREATE TABLE `A_racess` (
	`Raceid` int AUTO_INCREMENT NOT NULL,
	`Eventid` int NOT NULL DEFAULT 0,
	`Seasoncode` int NOT NULL DEFAULT 0,
	`Racecodex` int unsigned,
	`Disciplineid` tinyint,
	`Disciplinecode` char(8),
	`Catcode` varchar(8),
	`Catcode2` varchar(5),
	`Catcode3` varchar(5),
	`Catcode4` varchar(5),
	`Gender` char(1),
	`Racedate` date,
	`Starteventdate` date,
	`Description` varchar(80),
	`Place` varchar(40),
	`Nationcode` varchar(5),
	`Td1id` int,
	`Td1name` varchar(80),
	`Td1nation` char(3),
	`Td1code` int,
	`Td2id` int,
	`Td2name` varchar(80),
	`Td2nation` char(3),
	`Td2code` int,
	`Calstatuscode` char(1),
	`Procstatuscode` char(1),
	`Receiveddate` date,
	`Pursuit` tinyint,
	`Masse` tinyint,
	`Relay` tinyint,
	`Distance` varchar(10),
	`Hill` varchar(10),
	`Style` char(1),
	`Qualif` tinyint,
	`Finale` tinyint,
	`Homol` varchar(20),
	`Webcomment` varchar(40),
	`Displaystatus` varchar(15),
	`Fisinterncomment` varchar(30),
	`Published` tinyint,
	`Validforfispoints` tinyint,
	`Usedfislist` int,
	`Tolist` int,
	`Discforlistcode` char(8),
	`Calculatedpenalty` decimal(10,2),
	`Appliedpenalty` decimal(10,2),
	`Appliedscala` int,
	`Penscafixed` tinyint,
	`Version` int,
	`Nationraceid` int,
	`Provraceid` int,
	`Msql7evid` int,
	`Mssql7id` int,
	`Results` tinyint DEFAULT 0,
	`Pdf` tinyint DEFAULT 0,
	`Topbanner` int,
	`Bottombanner` int,
	`Toplogo` int,
	`Bottomlogo` int,
	`Gallery` int,
	`Indi` tinyint DEFAULT 0,
	`Team` tinyint DEFAULT 0,
	`Tabcount` int unsigned DEFAULT 0,
	`Columncount` int unsigned DEFAULT 0,
	`Level` varchar(10) DEFAULT '',
	`Hloc1` varchar(10),
	`Hloc2` varchar(10),
	`Hloc3` varchar(10),
	`Hcet1` varchar(10),
	`Hcet2` varchar(10),
	`Hcet3` varchar(10),
	`Live` tinyint,
	`Livestatus1` varchar(30),
	`Livestatus2` varchar(30),
	`Livestatus3` varchar(30),
	`Liveinfo1` varchar(255),
	`Liveinfo2` varchar(255),
	`Liveinfo3` varchar(255),
	`Passwd` varchar(10),
	`Timinglogo` varchar(15),
	`Validdate` date,
	`Noepr` int NOT NULL DEFAULT 0,
	`TDdoc` int DEFAULT 0,
	`Timingreport` int DEFAULT 0,
	`Special_cup_points` int DEFAULT 0,
	`Skip_wcsl` int DEFAULT 0,
	`Validforowg` int unsigned NOT NULL DEFAULT 0,
	`Lastupdate` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `A_racess_Raceid` PRIMARY KEY(`Raceid`)
);
--> statement-breakpoint
CREATE TABLE `A_racetm` (
	`Raceid` int AUTO_INCREMENT NOT NULL,
	`Eventid` int NOT NULL DEFAULT 0,
	`Seasoncode` int NOT NULL DEFAULT 0,
	`Racecodex` int unsigned,
	`Disciplineid` tinyint,
	`Disciplinecode` char(8),
	`Catcode` varchar(8),
	`Catcode2` varchar(5),
	`Catcode3` varchar(5),
	`Catcode4` varchar(5),
	`Gender` char(1),
	`Racedate` date,
	`Starteventdate` date,
	`Description` varchar(80),
	`Place` varchar(40),
	`Nationcode` varchar(5),
	`Td1id` int,
	`Td1name` varchar(80),
	`Td1nation` char(3),
	`Td1code` int,
	`Td2id` int,
	`Td2name` varchar(80),
	`Td2nation` char(3),
	`Td2code` int,
	`Calstatuscode` char(1),
	`Procstatuscode` char(1),
	`Receiveddate` date,
	`Pursuit` tinyint,
	`Masse` tinyint,
	`Relay` tinyint,
	`Distance` varchar(10),
	`Hill` varchar(10),
	`Style` char(1),
	`Qualif` tinyint,
	`Finale` tinyint,
	`Homol` varchar(20),
	`Webcomment` varchar(40),
	`Displaystatus` varchar(15),
	`Fisinterncomment` varchar(30),
	`Published` tinyint,
	`Validforfispoints` tinyint,
	`Usedfislist` int,
	`Tolist` int,
	`Discforlistcode` char(8),
	`Calculatedpenalty` decimal(10,2),
	`Appliedpenalty` decimal(10,2),
	`Appliedscala` int,
	`Penscafixed` tinyint,
	`Version` int,
	`Nationraceid` int,
	`Provraceid` int,
	`Msql7evid` int,
	`Mssql7id` int,
	`Results` tinyint DEFAULT 0,
	`Pdf` tinyint DEFAULT 0,
	`Topbanner` int,
	`Bottombanner` int,
	`Toplogo` int,
	`Bottomlogo` int,
	`Gallery` int,
	`Indi` tinyint DEFAULT 0,
	`Team` tinyint DEFAULT 0,
	`Tabcount` int unsigned DEFAULT 0,
	`Columncount` int unsigned DEFAULT 0,
	`Level` varchar(10) DEFAULT '',
	`Hloc1` varchar(10),
	`Hloc2` varchar(10),
	`Hloc3` varchar(10),
	`Hcet1` varchar(10),
	`Hcet2` varchar(10),
	`Hcet3` varchar(10),
	`Live` tinyint,
	`Livestatus1` varchar(30),
	`Livestatus2` varchar(30),
	`Livestatus3` varchar(30),
	`Liveinfo1` varchar(255),
	`Liveinfo2` varchar(255),
	`Liveinfo3` varchar(255),
	`Passwd` varchar(10),
	`Timinglogo` varchar(15),
	`Validdate` date,
	`Noepr` int NOT NULL DEFAULT 0,
	`TDdoc` int DEFAULT 0,
	`Timingreport` int DEFAULT 0,
	`Special_cup_points` int DEFAULT 0,
	`Skip_wcsl` int DEFAULT 0,
	`Validforowg` int unsigned NOT NULL DEFAULT 0,
	`Lastupdate` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `A_racetm_Raceid` PRIMARY KEY(`Raceid`)
);
--> statement-breakpoint
CREATE TABLE `A_resultal` (
	`Recid` int AUTO_INCREMENT NOT NULL,
	`Raceid` int NOT NULL DEFAULT 0,
	`Competitorid` int NOT NULL DEFAULT 0,
	`Status` varchar(5),
	`Reason` varchar(100),
	`Status2` varchar(5),
	`Position` int,
	`Bib` int,
	`Fiscode` int,
	`Competitorname` varchar(50),
	`Nationcode` varchar(5),
	`Level` tinyint,
	`Heat` tinyint,
	`Timer1` varchar(15),
	`Timer2` varchar(15),
	`Timer3` varchar(15),
	`Timetot` varchar(15),
	`Valid` tinyint,
	`Racepoints` decimal(10,2),
	`Cuppoints` decimal(10,2),
	`Version` int,
	`Timer1int` int DEFAULT 0,
	`Timer2int` int DEFAULT 0,
	`Timer3int` int DEFAULT 0,
	`Timetotint` int DEFAULT 0,
	`Racepointsreceived` varchar(15),
	`Listfispoints` decimal(10,2) DEFAULT '99999.99',
	`Ptsmax` int DEFAULT 99999,
	`Lastupdate` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `A_resultal_Recid` PRIMARY KEY(`Recid`)
);
--> statement-breakpoint
CREATE TABLE `A_resultcc` (
	`Recid` int AUTO_INCREMENT NOT NULL,
	`Raceid` int NOT NULL DEFAULT 0,
	`Competitorid` int NOT NULL DEFAULT 0,
	`Status` varchar(5),
	`Reason` varchar(100),
	`Position` int,
	`Pf` tinyint(1) DEFAULT 0,
	`Status2` varchar(20),
	`Bib` int,
	`Bibcolor` varchar(10),
	`Fiscode` int,
	`Competitorname` varchar(50),
	`Nationcode` varchar(5),
	`Stage` varchar(15),
	`Level` tinyint,
	`Heat` tinyint,
	`Timer1` varchar(15),
	`Timer2` varchar(15),
	`Timer3` varchar(15),
	`Timetot` varchar(15),
	`Valid` tinyint,
	`Racepoints` decimal(10,2),
	`Cuppoints` decimal(10,2),
	`Bonustime` varchar(15),
	`Bonuscuppoints` decimal(10,2),
	`Version` int,
	`Rg1` int,
	`Rg2` int,
	`Lastupdate` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `A_resultcc_Recid` PRIMARY KEY(`Recid`)
);
--> statement-breakpoint
CREATE TABLE `A_resultccteam` (
	`Recid` int AUTO_INCREMENT NOT NULL,
	`Raceid` int NOT NULL DEFAULT 0,
	`Teamid` int NOT NULL DEFAULT 0,
	`Competitorid` int NOT NULL DEFAULT 0,
	`Status` varchar(5),
	`Reason` varchar(100),
	`Position` int,
	`Status2` varchar(20),
	`Bib` int,
	`Bibcolor` varchar(10),
	`Leg` tinyint,
	`Fiscode` int,
	`Competitorname` varchar(50),
	`Nationcode` varchar(5),
	`Stage` varchar(15),
	`Level` tinyint,
	`Timer1` varchar(15),
	`Timer2` varchar(15),
	`Timer3` varchar(15),
	`Timetot` varchar(15),
	`Valid` tinyint,
	`Racepoints` decimal(10,2),
	`Cuppoints` decimal(10,2),
	`Version` int,
	`Leveltext` varchar(20),
	`Lastupdate` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	`Rg1` int,
	`Rg2` int,
	CONSTRAINT `A_resultccteam_Recid` PRIMARY KEY(`Recid`)
);
--> statement-breakpoint
CREATE TABLE `A_resultfs` (
	`Recid` int AUTO_INCREMENT NOT NULL,
	`Raceid` int NOT NULL DEFAULT 0,
	`Competitorid` int NOT NULL DEFAULT 0,
	`Status` varchar(5),
	`Reason` varchar(100),
	`Status2` varchar(5),
	`Position` int,
	`Bib` int,
	`Fiscode` int,
	`Competitorname` varchar(50),
	`Nationcode` varchar(5),
	`Level` tinyint,
	`Heat` tinyint,
	`Stage` varchar(10),
	`J1r1` varchar(6),
	`J2r1` varchar(6),
	`J3r1` varchar(6),
	`J4r1` varchar(6),
	`J5r1` varchar(6),
	`Totr1` varchar(15),
	`J1r2` varchar(6),
	`J2r2` varchar(6),
	`J3r2` varchar(6),
	`J4r2` varchar(6),
	`J5r2` varchar(6),
	`Totr2` varchar(15),
	`Tot` varchar(15),
	`Valid` tinyint,
	`Racepoints` decimal(10,2),
	`Cuppoints` decimal(10,2),
	`Details` text,
	`Version` int,
	`Lastupdate` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `A_resultfs_Recid` PRIMARY KEY(`Recid`)
);
--> statement-breakpoint
CREATE TABLE `A_resultgs` (
	`Recid` int AUTO_INCREMENT NOT NULL,
	`Raceid` int NOT NULL DEFAULT 0,
	`Competitorid` int NOT NULL DEFAULT 0,
	`Status` varchar(5),
	`Reason` varchar(100),
	`Status2` varchar(5),
	`Position` int,
	`Bib` int,
	`Fiscode` int,
	`Competitorname` varchar(50),
	`Nationcode` varchar(5),
	`Level` tinyint,
	`Heat` tinyint,
	`Timer1` varchar(15),
	`Timer2` varchar(15),
	`Timer3` varchar(15),
	`Timetot` varchar(15),
	`Valid` tinyint,
	`Racepoints` decimal(10,2),
	`Cuppoints` decimal(10,2),
	`Version` int,
	`Timer1int` int DEFAULT 0,
	`Timer2int` int DEFAULT 0,
	`Timer3int` int DEFAULT 0,
	`Timetotint` int DEFAULT 0,
	`Racepointsreceived` varchar(15),
	`Listfispoints` decimal(10,2),
	`Ptsmax` int DEFAULT 99999,
	`Lastupdate` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `A_resultgs_Recid` PRIMARY KEY(`Recid`)
);
--> statement-breakpoint
CREATE TABLE `A_resultjp` (
	`Recid` int AUTO_INCREMENT NOT NULL,
	`Raceid` int NOT NULL DEFAULT 0,
	`Competitorid` int NOT NULL DEFAULT 0,
	`Status` varchar(5),
	`Status2` varchar(20),
	`Position` int,
	`Bib` int,
	`Fiscode` int,
	`Competitorname` varchar(50),
	`Nationcode` varchar(5),
	`Level` tinyint,
	`Heat` tinyint,
	`Stage` varchar(10),
	`J1r1` varchar(6),
	`J2r1` varchar(6),
	`J3r1` varchar(6),
	`J4r1` varchar(6),
	`J5r1` varchar(6),
	`Speedr1` varchar(6),
	`Distr1` varchar(6),
	`Disptsr1` varchar(6),
	`Judptsr1` varchar(6),
	`Totrun1` varchar(6),
	`Posr1` varchar(6),
	`Statusr1` varchar(20),
	`J1r2` varchar(6),
	`J2r2` varchar(6),
	`J3r2` varchar(6),
	`J4r2` varchar(6),
	`J5r2` varchar(6),
	`Speedr2` varchar(6),
	`Distr2` varchar(6),
	`Disptsr2` varchar(6),
	`Judptsr2` varchar(6),
	`Totrun2` varchar(6),
	`Posr2` varchar(6),
	`Statusr2` varchar(20),
	`J1r3` varchar(6),
	`J2r3` varchar(6),
	`J3r3` varchar(6),
	`J4r3` varchar(6),
	`J5r3` varchar(6),
	`Speedr3` varchar(6),
	`Distr3` varchar(6),
	`Disptsr3` varchar(6),
	`Judptsr3` varchar(6),
	`Totrun3` varchar(6),
	`Posr3` varchar(6),
	`Statusr3` varchar(20),
	`J1r4` varchar(6),
	`J2r4` varchar(6),
	`J3r4` varchar(6),
	`J4r4` varchar(6),
	`J5r4` varchar(6),
	`Speedr4` varchar(6),
	`Distr4` varchar(6),
	`Disptsr4` varchar(6),
	`Judptsr4` varchar(6),
	`Gater1` varchar(6),
	`Gater2` varchar(6),
	`Gater3` varchar(6),
	`Gater4` varchar(6),
	`Gateptsr1` varchar(6),
	`Gateptsr2` varchar(6),
	`Gateptsr3` varchar(6),
	`Gateptsr4` varchar(6),
	`Windr1` varchar(6),
	`Windr2` varchar(6),
	`Windr3` varchar(6),
	`Windr4` varchar(6),
	`Windptsr1` varchar(6),
	`Windptsr2` varchar(6),
	`Windptsr3` varchar(6),
	`Windptsr4` varchar(6),
	`Reason` varchar(100),
	`Totrun4` varchar(6),
	`Tot` varchar(15),
	`Valid` tinyint,
	`Racepoints` decimal(10,2),
	`Cuppoints` decimal(10,2),
	`Version` int,
	`Lastupdate` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	`Posr4` varchar(6),
	`Statusr4` varchar(20),
	CONSTRAINT `A_resultjp_Recid` PRIMARY KEY(`Recid`)
);
--> statement-breakpoint
CREATE TABLE `A_resultjpteam` (
	`Recid` int AUTO_INCREMENT NOT NULL,
	`Raceid` int NOT NULL DEFAULT 0,
	`Teamid` int NOT NULL DEFAULT 0,
	`Competitorid` int NOT NULL DEFAULT 0,
	`Status` varchar(5),
	`Status2` varchar(20),
	`Position` int,
	`Bib` int,
	`Fiscode` int,
	`Competitorname` varchar(50),
	`Nationcode` varchar(5),
	`Level` tinyint,
	`Stage` varchar(10),
	`J1r1` varchar(6),
	`J2r1` varchar(6),
	`J3r1` varchar(6),
	`J4r1` varchar(6),
	`J5r1` varchar(6),
	`Speedr1` varchar(6),
	`Distr1` varchar(6),
	`Disptsr1` varchar(6),
	`Judptsr1` varchar(6),
	`Totrun1` varchar(6),
	`Posr1` varchar(6),
	`Statusr1` varchar(20),
	`J1r2` varchar(6),
	`J2r2` varchar(6),
	`J3r2` varchar(6),
	`J4r2` varchar(6),
	`J5r2` varchar(6),
	`Speedr2` varchar(6),
	`Distr2` varchar(6),
	`Disptsr2` varchar(6),
	`Judptsr2` varchar(6),
	`Totrun2` varchar(6),
	`Posr2` varchar(6),
	`Statusr2` varchar(20),
	`J1r3` varchar(6),
	`J2r3` varchar(6),
	`J3r3` varchar(6),
	`J4r3` varchar(6),
	`J5r3` varchar(6),
	`Speedr3` varchar(6),
	`Distr3` varchar(6),
	`Disptsr3` varchar(6),
	`Judptsr3` varchar(6),
	`Totrun3` varchar(6),
	`Posr3` varchar(6),
	`Statusr3` varchar(20),
	`J1r4` varchar(6),
	`J2r4` varchar(6),
	`J3r4` varchar(6),
	`J4r4` varchar(6),
	`J5r4` varchar(6),
	`Speedr4` varchar(6),
	`Distr4` varchar(6),
	`Disptsr4` varchar(6),
	`Judptsr4` varchar(6),
	`Totrun4` varchar(6),
	`Posr4` varchar(6),
	`Statusr4` varchar(20),
	`Tot` varchar(15),
	`Valid` tinyint,
	`Racepoints` decimal(10,2),
	`Cuppoints` decimal(10,2),
	`Version` int,
	`Lastupdate` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `A_resultjpteam_Recid` PRIMARY KEY(`Recid`)
);
--> statement-breakpoint
CREATE TABLE `A_resultma` (
	`Recid` int AUTO_INCREMENT NOT NULL,
	`Raceid` int NOT NULL DEFAULT 0,
	`Competitorid` int NOT NULL DEFAULT 0,
	`Status` varchar(5),
	`Reason` varchar(100),
	`Status2` varchar(5),
	`Position` int,
	`Bib` int,
	`Fiscode` int,
	`Competitorname` varchar(50),
	`Nationcode` varchar(5),
	`Level` tinyint,
	`Heat` tinyint,
	`Timer1` varchar(15),
	`Timer2` varchar(15),
	`Timer3` varchar(15),
	`Timetot` varchar(15),
	`Valid` tinyint,
	`Racepoints` decimal(10,2),
	`Cuppoints` decimal(10,2) DEFAULT '0.00',
	`Version` int,
	`Catage` int,
	`Age` int,
	`Rangcat` int,
	`Cuppointscat` decimal(10,2) unsigned,
	`Handicap_timetot` varchar(15),
	`Handicap_rank` tinyint unsigned,
	`Lastupdate` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `A_resultma_Recid` PRIMARY KEY(`Recid`)
);
--> statement-breakpoint
CREATE TABLE `A_resultnk` (
	`Recid` int AUTO_INCREMENT NOT NULL,
	`Raceid` int NOT NULL DEFAULT 0,
	`Competitorid` int NOT NULL DEFAULT 0,
	`Status` varchar(5),
	`Reason` varchar(100),
	`Position` int,
	`Pf` tinyint(1) DEFAULT 0,
	`Status2` varchar(20),
	`Bib` int,
	`Bibcolor` varchar(10),
	`Fiscode` int,
	`Competitorname` varchar(50),
	`Nationcode` varchar(5),
	`Level` tinyint,
	`Heat` tinyint,
	`Stage` varchar(10),
	`J1r1` varchar(6),
	`J2r1` varchar(6),
	`J3r1` varchar(6),
	`J4r1` varchar(6),
	`J5r1` varchar(6),
	`Speedr1` varchar(6),
	`Distr1` varchar(6),
	`Disptsr1` varchar(6),
	`Judptsr1` varchar(6),
	`Gater1` varchar(6),
	`Gateptsr1` varchar(6),
	`Windr1` varchar(6),
	`Windptsr1` varchar(6),
	`Totrun1` varchar(6),
	`Posr1` varchar(6),
	`Statusr1` varchar(20),
	`J1r2` varchar(6),
	`J2r2` varchar(6),
	`J3r2` varchar(6),
	`J4r2` varchar(6),
	`J5r2` varchar(6),
	`Speedr2` varchar(6),
	`Distr2` varchar(6),
	`Disptsr2` varchar(6),
	`Judptsr2` varchar(6),
	`Gater2` varchar(6),
	`Gateptsr2` varchar(6),
	`Windr2` varchar(6),
	`Windptsr2` varchar(6),
	`Totrun2` varchar(6),
	`Posr2` varchar(6),
	`Statusr2` varchar(20),
	`Pointsjump` varchar(15),
	`Behindjump` varchar(15),
	`Posjump` varchar(6),
	`Timecc` varchar(15),
	`Timeccint` int,
	`Poscc` varchar(6),
	`Starttime` varchar(5),
	`Statuscc` varchar(20),
	`Totbehind` varchar(15),
	`Timetot` varchar(15),
	`Timetotint` int,
	`Valid` tinyint,
	`Racepoints` decimal(10,2),
	`Cuppoints` decimal(10,2),
	`Version` int,
	`Lastupdate` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `A_resultnk_Recid` PRIMARY KEY(`Recid`)
);
--> statement-breakpoint
CREATE TABLE `A_resultnkteam` (
	`Recid` int AUTO_INCREMENT NOT NULL,
	`Raceid` int NOT NULL DEFAULT 0,
	`Teamid` int NOT NULL DEFAULT 0,
	`Competitorid` int NOT NULL DEFAULT 0,
	`Status` varchar(5),
	`Reason` varchar(100),
	`Position` int,
	`Pf` tinyint(1) DEFAULT 0,
	`Status2` varchar(20),
	`Bib` int,
	`Bibcolor` varchar(10),
	`Leg` tinyint,
	`Fiscode` int,
	`Competitorname` varchar(50),
	`Nationcode` varchar(5),
	`Level` tinyint,
	`Stage` varchar(10),
	`J1r1` varchar(6),
	`J2r1` varchar(6),
	`J3r1` varchar(6),
	`J4r1` varchar(6),
	`J5r1` varchar(6),
	`Speedr1` varchar(6),
	`Distr1` varchar(6),
	`Disptsr1` varchar(6),
	`Judptsr1` varchar(6),
	`Gater1` varchar(6),
	`Gateptsr1` varchar(6),
	`Windr1` varchar(6),
	`Windptsr1` varchar(6),
	`Totrun1` varchar(6),
	`Posr1` varchar(6),
	`Statusr1` varchar(20),
	`J1r2` varchar(6),
	`J2r2` varchar(6),
	`J3r2` varchar(6),
	`J4r2` varchar(6),
	`J5r2` varchar(6),
	`Speedr2` varchar(6),
	`Distr2` varchar(6),
	`Disptsr2` varchar(6),
	`Judptsr2` varchar(6),
	`Gater2` varchar(6),
	`Gateptsr2` varchar(6),
	`Windr2` varchar(6),
	`Windptsr2` varchar(6),
	`Totrun2` varchar(6),
	`Posr2` varchar(6),
	`Statusr2` varchar(20),
	`Pointsjump` varchar(15),
	`Behindjump` varchar(15),
	`Posjump` varchar(6),
	`Timecc` varchar(15),
	`Timeccint` int,
	`Poscc` varchar(6),
	`Starttime` varchar(5),
	`Statuscc` varchar(20),
	`Totbehind` varchar(15),
	`Valid` tinyint,
	`Racepoints` decimal(10,2),
	`Cuppoints` decimal(10,2),
	`Version` int,
	`Leveltext` varchar(20),
	`Lastupdate` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `A_resultnkteam_Recid` PRIMARY KEY(`Recid`)
);
--> statement-breakpoint
CREATE TABLE `A_resultsb` (
	`Recid` int AUTO_INCREMENT NOT NULL,
	`Raceid` int NOT NULL DEFAULT 0,
	`Competitorid` int NOT NULL DEFAULT 0,
	`Status` varchar(5),
	`Reason` varchar(100),
	`Status2` varchar(5),
	`Position` int,
	`Bib` int,
	`Fiscode` int,
	`Competitorname` varchar(50),
	`Nationcode` varchar(5),
	`Level` tinyint,
	`Heat` tinyint,
	`Stage` varchar(10),
	`J1r1` varchar(6),
	`J2r1` varchar(6),
	`J3r1` varchar(6),
	`J4r1` varchar(6),
	`J5r1` varchar(6),
	`Totr1` varchar(15),
	`J1r2` varchar(6),
	`J2r2` varchar(6),
	`J3r2` varchar(6),
	`J4r2` varchar(6),
	`J5r2` varchar(6),
	`Totr2` varchar(15),
	`J1r3` varchar(6),
	`J2r3` varchar(6),
	`J3r3` varchar(6),
	`J4r3` varchar(6),
	`J5r3` varchar(6),
	`Totr3` varchar(15),
	`Tot` varchar(15),
	`Valid` tinyint,
	`Racepoints` decimal(10,2),
	`Cuppoints` decimal(10,2),
	`Details` text,
	`Version` int,
	`Lastupdate` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `A_resultsb_Recid` PRIMARY KEY(`Recid`)
);
--> statement-breakpoint
CREATE TABLE `A_resultss` (
	`Recid` int AUTO_INCREMENT NOT NULL,
	`Raceid` int NOT NULL DEFAULT 0,
	`Competitorid` int NOT NULL DEFAULT 0,
	`Status` varchar(5),
	`Reason` varchar(100),
	`Status2` varchar(5),
	`Position` int,
	`Bib` int,
	`Fiscode` int,
	`Competitorname` varchar(50),
	`Nationcode` varchar(5),
	`Timer1` varchar(15),
	`Speedr1` decimal(10,2) DEFAULT '10.00',
	`Timer2` varchar(15),
	`Speedr2` decimal(10,2) DEFAULT '10.00',
	`Timer3` varchar(15),
	`Speedr3` decimal(10,2) DEFAULT '10.00',
	`Timer4` varchar(15),
	`Speedr4` decimal(10,2) DEFAULT '10.00',
	`Timer5` varchar(15),
	`Speedr5` decimal(10,2) DEFAULT '10.00',
	`Timetot` varchar(15),
	`Valid` tinyint,
	`Racepoints` decimal(10,2),
	`SpeedForFisPoints` decimal(10,2),
	`Cuppoints` decimal(10,2) DEFAULT '0.00',
	`Version` int,
	`NumberOfRuns` int NOT NULL DEFAULT 0,
	`Level` tinyint,
	`Heat` tinyint,
	`Category` int NOT NULL DEFAULT 1,
	`Rankcateg` int,
	`Speed` decimal(10,2),
	`Lastupdate` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `A_resultss_Recid` PRIMARY KEY(`Recid`)
);
--> statement-breakpoint
CREATE TABLE `A_resulttm` (
	`Recid` int AUTO_INCREMENT NOT NULL,
	`Raceid` int NOT NULL DEFAULT 0,
	`Competitorid` int NOT NULL DEFAULT 0,
	`Status` varchar(5),
	`Reason` varchar(100),
	`Status2` varchar(5),
	`Position` int,
	`Bib` int,
	`Fiscode` int,
	`Competitorname` varchar(50),
	`Nationcode` varchar(5),
	`Level` tinyint,
	`Heat` tinyint,
	`Timer1` varchar(15),
	`Timer2` varchar(15),
	`Timer3` varchar(15),
	`Timetot` varchar(15),
	`Valid` tinyint,
	`Racepoints` decimal(10,2),
	`Cuppoints` decimal(10,2),
	`Version` int,
	`Timer1int` int DEFAULT 0,
	`Timer2int` int DEFAULT 0,
	`Timer3int` int DEFAULT 0,
	`Timetotint` int DEFAULT 0,
	`racepointsreceived` varchar(15),
	`Listfispoints` decimal DEFAULT '999999',
	`Ptsmax` int DEFAULT 99999,
	`Lastupdate` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `A_resulttm_Recid` PRIMARY KEY(`Recid`)
);
--> statement-breakpoint
CREATE TABLE `A_sector` (
	`Recid` int AUTO_INCREMENT NOT NULL,
	`Sectorcode` char(3) NOT NULL,
	`Description` varchar(25) NOT NULL,
	`Iocsector` char(4),
	`Fispoints` tinyint,
	`Displayorder` tinyint unsigned NOT NULL DEFAULT 0,
	`Others` tinyint,
	`Lastupdate` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `A_sector_Recid` PRIMARY KEY(`Recid`)
);
--> statement-breakpoint
CREATE INDEX `Namegen` ON `A_competitor` (`Sectorcode`,`Gender`,`Lastname`,`Firstname`);--> statement-breakpoint
CREATE INDEX `Name` ON `A_competitor` (`Sectorcode`,`Lastname`,`Firstname`);--> statement-breakpoint
CREATE INDEX `SectorName` ON `A_competitor` (`Sectorcode`,`Gender`,`Status`,`Lastname`,`Firstname`);--> statement-breakpoint
CREATE INDEX `Fiscode` ON `A_competitor` (`Sectorcode`,`Fiscode`);--> statement-breakpoint
CREATE INDEX `datec` ON `A_competitor` (`Sectorcode`,`Dateofcreation`,`Competitorid`);--> statement-breakpoint
CREATE INDEX `Oldid` ON `A_competitor` (`Compidmssql`);--> statement-breakpoint
CREATE INDEX `LastFirstFiscodeCompid` ON `A_competitor` (`Competitorid`,`Sectorcode`,`Fiscode`,`Lastname`,`Firstname`);--> statement-breakpoint
CREATE INDEX `LastFirstGenFiscodeCompid` ON `A_competitor` (`Competitorid`,`Sectorcode`,`Fiscode`,`Lastname`,`Firstname`,`Gender`);--> statement-breakpoint
CREATE INDEX `A_competitor_Ipcid_index` ON `A_competitor` (`Ipcid`);--> statement-breakpoint
CREATE INDEX `A_competitor_Personid_index` ON `A_competitor` (`Personid`);--> statement-breakpoint
CREATE INDEX `idx_competitor_competitorid` ON `A_competitor` (`Competitorid`);--> statement-breakpoint
CREATE INDEX `cup` ON `A_cup` (`Sectorcode`,`Cupcode`);--> statement-breakpoint
CREATE INDEX `Cup` ON `A_cupresult` (`Seasoncode`,`Sectorcode`,`Cupid`,`Disciplinecode`,`Afterxrace`,`Competitorid`);--> statement-breakpoint
CREATE INDEX `Compet` ON `A_cupresult` (`Competitorid`,`Seasoncode`,`Cupid`,`Disciplinecode`,`Afterxrace`);--> statement-breakpoint
CREATE INDEX `idx_cupcompsect` ON `A_cupresult` (`Competitorid`,`Sectorcode`);--> statement-breakpoint
CREATE INDEX `disc` ON `A_discipline` (`Sectorcode`,`Disciplinecode`);--> statement-breakpoint
CREATE INDEX `id` ON `A_discipline` (`Disciplineid`);--> statement-breakpoint
CREATE INDEX `ordre` ON `A_discipline` (`Sectorcode`,`Displayorder`);--> statement-breakpoint
CREATE INDEX `Eventdate` ON `A_event` (`Sectorcode`,`Seasoncode`,`Startdate`,`Eventid`);--> statement-breakpoint
CREATE INDEX `Eventplace` ON `A_event` (`Sectorcode`,`Place`,`Startdate`,`Eventid`);--> statement-breakpoint
CREATE INDEX `Eventnation` ON `A_event` (`Sectorcode`,`Seasoncode`,`Orgnationcode`,`Startdate`,`Eventid`);--> statement-breakpoint
CREATE INDEX `idxLastupdate` ON `A_event` (`Lastupdate`);--> statement-breakpoint
CREATE INDEX `categ` ON `A_listcategoryal` (`Listid`,`Catcode`,`Gender`);--> statement-breakpoint
CREATE INDEX `categ` ON `A_listcategorycc` (`Listid`,`Catcode`,`Gender`);--> statement-breakpoint
CREATE INDEX `categ` ON `A_listcategoryfs` (`Listid`,`Catcode`,`Gender`);--> statement-breakpoint
CREATE INDEX `categ` ON `A_listcategorygs` (`Listid`,`Catcode`,`Gender`);--> statement-breakpoint
CREATE INDEX `categ` ON `A_listcategoryma` (`Listid`,`Catcode`,`Gender`);--> statement-breakpoint
CREATE INDEX `categ` ON `A_listcategorysb` (`Listid`,`Catcode`,`Gender`);--> statement-breakpoint
CREATE INDEX `categ` ON `A_listcategoryss` (`Listid`,`Catcode`,`Gender`);--> statement-breakpoint
CREATE INDEX `categ` ON `A_listcategorytm` (`Listid`,`Catcode`,`Gender`);--> statement-breakpoint
CREATE INDEX `list` ON `A_listdefal` (`Seasoncode`,`Listnumber`);--> statement-breakpoint
CREATE INDEX `list` ON `A_listdefcc` (`Seasoncode`,`Listnumber`);--> statement-breakpoint
CREATE INDEX `list` ON `A_listdeffs` (`Seasoncode`,`Listnumber`);--> statement-breakpoint
CREATE INDEX `list` ON `A_listdefgs` (`Seasoncode`,`Listnumber`);--> statement-breakpoint
CREATE INDEX `list` ON `A_listdefma` (`Seasoncode`,`Listnumber`);--> statement-breakpoint
CREATE INDEX `list` ON `A_listdefsb` (`Seasoncode`,`Listnumber`);--> statement-breakpoint
CREATE INDEX `list` ON `A_listdefss` (`Seasoncode`,`Listnumber`);--> statement-breakpoint
CREATE INDEX `list` ON `A_listdeftm` (`Seasoncode`,`Listnumber`);--> statement-breakpoint
CREATE INDEX `disc` ON `A_listdisciplineal` (`Listid`,`Disciplinecode`,`Gender`);--> statement-breakpoint
CREATE INDEX `disc` ON `A_listdisciplinetm` (`Listid`,`Disciplinecode`,`Gender`);--> statement-breakpoint
CREATE INDEX `compet` ON `A_listresultal` (`Listid`,`Competitorid`,`Disciplinecode`);--> statement-breakpoint
CREATE INDEX `rank` ON `A_listresultal` (`Listid`,`Disciplinecode`,`Position`);--> statement-breakpoint
CREATE INDEX `compet` ON `A_listresultcc` (`Listid`,`Competitorid`,`Disciplinecode`);--> statement-breakpoint
CREATE INDEX `rank` ON `A_listresultcc` (`Listid`,`Disciplinecode`,`Position`);--> statement-breakpoint
CREATE INDEX `compet` ON `A_listresultfs` (`Listid`,`Competitorid`,`Disciplinecode`);--> statement-breakpoint
CREATE INDEX `rank` ON `A_listresultfs` (`Listid`,`Disciplinecode`,`Position`);--> statement-breakpoint
CREATE INDEX `compet` ON `A_listresultgs` (`Listid`,`Competitorid`,`Disciplinecode`);--> statement-breakpoint
CREATE INDEX `rank` ON `A_listresultgs` (`Listid`,`Disciplinecode`,`Position`);--> statement-breakpoint
CREATE INDEX `compet` ON `A_listresultma` (`Listid`,`Competitorid`,`Disciplinecode`);--> statement-breakpoint
CREATE INDEX `rank` ON `A_listresultma` (`Listid`,`Disciplinecode`,`Position`);--> statement-breakpoint
CREATE INDEX `compet` ON `A_listresultsb` (`Listid`,`Competitorid`,`Disciplinecode`);--> statement-breakpoint
CREATE INDEX `rank` ON `A_listresultsb` (`Listid`,`Disciplinecode`,`Position`);--> statement-breakpoint
CREATE INDEX `compet` ON `A_listresultss` (`Listid`,`Competitorid`,`Disciplinecode`);--> statement-breakpoint
CREATE INDEX `rank` ON `A_listresultss` (`Listid`,`Disciplinecode`,`Position`);--> statement-breakpoint
CREATE INDEX `Evrace` ON `A_raceal` (`Eventid`,`Raceid`);--> statement-breakpoint
CREATE INDEX `Evracefull` ON `A_raceal` (`Seasoncode`,`Eventid`,`Racedate`);--> statement-breakpoint
CREATE INDEX `Codex` ON `A_raceal` (`Seasoncode`,`Racecodex`);--> statement-breakpoint
CREATE INDEX `idxLastupdate` ON `A_raceal` (`Lastupdate`);--> statement-breakpoint
CREATE INDEX `idx_eventid` ON `A_raceal` (`Eventid`);--> statement-breakpoint
CREATE INDEX `Evrace` ON `A_racecc` (`Eventid`,`Raceid`);--> statement-breakpoint
CREATE INDEX `Evracefull` ON `A_racecc` (`Seasoncode`,`Eventid`,`Racedate`);--> statement-breakpoint
CREATE INDEX `Codex` ON `A_racecc` (`Seasoncode`,`Racecodex`);--> statement-breakpoint
CREATE INDEX `sql7` ON `A_racecc` (`Mssql7id`);--> statement-breakpoint
CREATE INDEX `provid` ON `A_racecc` (`Provraceid`);--> statement-breakpoint
CREATE INDEX `idx_catcode_seasoncode_gender_disciplinecode` ON `A_racecc` (`Catcode`,`Seasoncode`,`Gender`);--> statement-breakpoint
CREATE INDEX `idx_level` ON `A_racecc` (`Level`);--> statement-breakpoint
CREATE INDEX `idx_eventid` ON `A_racecc` (`Eventid`);--> statement-breakpoint
CREATE INDEX `Evrace` ON `A_racefs` (`Eventid`,`Raceid`);--> statement-breakpoint
CREATE INDEX `Evracefull` ON `A_racefs` (`Seasoncode`,`Eventid`,`Racedate`);--> statement-breakpoint
CREATE INDEX `Codex` ON `A_racefs` (`Seasoncode`,`Racecodex`);--> statement-breakpoint
CREATE INDEX `sql7` ON `A_racefs` (`Mssql7id`);--> statement-breakpoint
CREATE INDEX `provid` ON `A_racefs` (`Provraceid`);--> statement-breakpoint
CREATE INDEX `idx_eventid` ON `A_racefs` (`Eventid`);--> statement-breakpoint
CREATE INDEX `Evrace` ON `A_racejp` (`Eventid`,`Raceid`);--> statement-breakpoint
CREATE INDEX `Evracefull` ON `A_racejp` (`Seasoncode`,`Eventid`,`Racedate`);--> statement-breakpoint
CREATE INDEX `Codex` ON `A_racejp` (`Seasoncode`,`Racecodex`);--> statement-breakpoint
CREATE INDEX `sql7` ON `A_racejp` (`Mssql7id`);--> statement-breakpoint
CREATE INDEX `provid` ON `A_racejp` (`Provraceid`);--> statement-breakpoint
CREATE INDEX `idx_eventid` ON `A_racejp` (`Eventid`);--> statement-breakpoint
CREATE INDEX `Evrace` ON `A_racema` (`Eventid`,`Raceid`);--> statement-breakpoint
CREATE INDEX `Evracefull` ON `A_racema` (`Seasoncode`,`Eventid`,`Racedate`);--> statement-breakpoint
CREATE INDEX `Codex` ON `A_racema` (`Seasoncode`,`Racecodex`);--> statement-breakpoint
CREATE INDEX `sql7` ON `A_racema` (`Mssql7id`);--> statement-breakpoint
CREATE INDEX `provid` ON `A_racema` (`Provraceid`);--> statement-breakpoint
CREATE INDEX `idx_eventid` ON `A_racema` (`Eventid`);--> statement-breakpoint
CREATE INDEX `Evrace` ON `A_racenk` (`Eventid`,`Raceid`);--> statement-breakpoint
CREATE INDEX `Evracefull` ON `A_racenk` (`Seasoncode`,`Eventid`,`Racedate`);--> statement-breakpoint
CREATE INDEX `Codex` ON `A_racenk` (`Seasoncode`,`Racecodex`);--> statement-breakpoint
CREATE INDEX `sql7` ON `A_racenk` (`Mssql7id`);--> statement-breakpoint
CREATE INDEX `provid` ON `A_racenk` (`Provraceid`);--> statement-breakpoint
CREATE INDEX `idx_eventid` ON `A_racenk` (`Eventid`);--> statement-breakpoint
CREATE INDEX `Evrace` ON `A_racesb` (`Eventid`,`Raceid`);--> statement-breakpoint
CREATE INDEX `Evracefull` ON `A_racesb` (`Seasoncode`,`Eventid`,`Racedate`);--> statement-breakpoint
CREATE INDEX `Codex` ON `A_racesb` (`Seasoncode`,`Racecodex`);--> statement-breakpoint
CREATE INDEX `sql7` ON `A_racesb` (`Mssql7id`);--> statement-breakpoint
CREATE INDEX `provid` ON `A_racesb` (`Provraceid`);--> statement-breakpoint
CREATE INDEX `idx_eventid` ON `A_racesb` (`Eventid`);--> statement-breakpoint
CREATE INDEX `Evrace` ON `A_racess` (`Eventid`,`Raceid`);--> statement-breakpoint
CREATE INDEX `Evracefull` ON `A_racess` (`Seasoncode`,`Eventid`,`Racedate`);--> statement-breakpoint
CREATE INDEX `Codex` ON `A_racess` (`Seasoncode`,`Racecodex`);--> statement-breakpoint
CREATE INDEX `sql7` ON `A_racess` (`Mssql7id`);--> statement-breakpoint
CREATE INDEX `provid` ON `A_racess` (`Provraceid`);--> statement-breakpoint
CREATE INDEX `idx_eventid` ON `A_racess` (`Eventid`);--> statement-breakpoint
CREATE INDEX `Evrace` ON `A_racetm` (`Eventid`,`Raceid`);--> statement-breakpoint
CREATE INDEX `Evracefull` ON `A_racetm` (`Seasoncode`,`Eventid`,`Racedate`);--> statement-breakpoint
CREATE INDEX `Codex` ON `A_racetm` (`Seasoncode`,`Racecodex`);--> statement-breakpoint
CREATE INDEX `sql7` ON `A_racetm` (`Mssql7id`);--> statement-breakpoint
CREATE INDEX `provid` ON `A_racetm` (`Provraceid`);--> statement-breakpoint
CREATE INDEX `idx_eventid` ON `A_racetm` (`Eventid`);--> statement-breakpoint
CREATE INDEX `Compet` ON `A_resultal` (`Competitorid`,`Raceid`);--> statement-breakpoint
CREATE INDEX `Race` ON `A_resultal` (`Raceid`,`Competitorid`);--> statement-breakpoint
CREATE INDEX `Raceid` ON `A_resultal` (`Raceid`);--> statement-breakpoint
CREATE INDEX `idxLastupdate` ON `A_resultal` (`Lastupdate`);--> statement-breakpoint
CREATE INDEX `Compet` ON `A_resultcc` (`Competitorid`,`Raceid`);--> statement-breakpoint
CREATE INDEX `Race` ON `A_resultcc` (`Raceid`,`Competitorid`);--> statement-breakpoint
CREATE INDEX `Raceid` ON `A_resultcc` (`Raceid`);--> statement-breakpoint
CREATE INDEX `Competitorid` ON `A_resultcc` (`Competitorid`);--> statement-breakpoint
CREATE INDEX `idx_cuppoints_status` ON `A_resultcc` (`Cuppoints`,`Status`);--> statement-breakpoint
CREATE INDEX `idx_competitorid_cuppoints` ON `A_resultcc` (`Competitorid`,`Cuppoints`);--> statement-breakpoint
CREATE INDEX `Compet` ON `A_resultccteam` (`Competitorid`,`Raceid`);--> statement-breakpoint
CREATE INDEX `Race` ON `A_resultccteam` (`Raceid`,`Competitorid`);--> statement-breakpoint
CREATE INDEX `Raceid` ON `A_resultccteam` (`Raceid`);--> statement-breakpoint
CREATE INDEX `Compet` ON `A_resultfs` (`Competitorid`,`Raceid`);--> statement-breakpoint
CREATE INDEX `Race` ON `A_resultfs` (`Raceid`,`Competitorid`);--> statement-breakpoint
CREATE INDEX `Raceid` ON `A_resultfs` (`Raceid`);--> statement-breakpoint
CREATE INDEX `Compet` ON `A_resultgs` (`Competitorid`,`Raceid`);--> statement-breakpoint
CREATE INDEX `Race` ON `A_resultgs` (`Raceid`,`Competitorid`);--> statement-breakpoint
CREATE INDEX `Raceid` ON `A_resultgs` (`Raceid`);--> statement-breakpoint
CREATE INDEX `Compet` ON `A_resultjp` (`Competitorid`,`Raceid`);--> statement-breakpoint
CREATE INDEX `Race` ON `A_resultjp` (`Raceid`,`Competitorid`);--> statement-breakpoint
CREATE INDEX `Raceid` ON `A_resultjp` (`Raceid`);--> statement-breakpoint
CREATE INDEX `Compet` ON `A_resultjpteam` (`Competitorid`,`Raceid`);--> statement-breakpoint
CREATE INDEX `Race` ON `A_resultjpteam` (`Raceid`,`Teamid`,`Competitorid`);--> statement-breakpoint
CREATE INDEX `Raceid` ON `A_resultjpteam` (`Raceid`);--> statement-breakpoint
CREATE INDEX `Compet` ON `A_resultma` (`Competitorid`,`Raceid`);--> statement-breakpoint
CREATE INDEX `Race` ON `A_resultma` (`Raceid`,`Competitorid`);--> statement-breakpoint
CREATE INDEX `Racid` ON `A_resultma` (`Raceid`);--> statement-breakpoint
CREATE INDEX `Compet` ON `A_resultnk` (`Competitorid`,`Raceid`);--> statement-breakpoint
CREATE INDEX `Race` ON `A_resultnk` (`Raceid`,`Competitorid`);--> statement-breakpoint
CREATE INDEX `Racid` ON `A_resultnk` (`Raceid`);--> statement-breakpoint
CREATE INDEX `Compet` ON `A_resultnkteam` (`Competitorid`,`Raceid`);--> statement-breakpoint
CREATE INDEX `Race` ON `A_resultnkteam` (`Raceid`,`Competitorid`);--> statement-breakpoint
CREATE INDEX `Raceid` ON `A_resultnkteam` (`Raceid`);--> statement-breakpoint
CREATE INDEX `Compet` ON `A_resultsb` (`Competitorid`,`Raceid`);--> statement-breakpoint
CREATE INDEX `Race` ON `A_resultsb` (`Raceid`,`Competitorid`);--> statement-breakpoint
CREATE INDEX `Raceid` ON `A_resultsb` (`Raceid`);--> statement-breakpoint
CREATE INDEX `Compet` ON `A_resultss` (`Competitorid`,`Raceid`);--> statement-breakpoint
CREATE INDEX `Race` ON `A_resultss` (`Raceid`,`Competitorid`);--> statement-breakpoint
CREATE INDEX `Raceid` ON `A_resultss` (`Raceid`);--> statement-breakpoint
CREATE INDEX `Compet` ON `A_resulttm` (`Competitorid`,`Raceid`);--> statement-breakpoint
CREATE INDEX `Race` ON `A_resulttm` (`Raceid`,`Competitorid`);--> statement-breakpoint
CREATE INDEX `Raceid` ON `A_resulttm` (`Raceid`);--> statement-breakpoint
CREATE INDEX `ordre` ON `A_sector` (`Displayorder`,`Sectorcode`);--> statement-breakpoint
CREATE INDEX `sector` ON `A_sector` (`Sectorcode`);
*/