name: Daily Recap

on:
  schedule:
    - cron: "0 18 * * *" # tous les jours à 18h UTC
  workflow_dispatch:

jobs:
  recap:
    runs-on: ubuntu-latest
    env:
      NEON_DATABASE_URL: ${{ secrets.NEON_DATABASE_URL }}
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm tsx scripts/daily-recap.ts
